<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/1090%EC%98%88%EC%B8%A1Lotto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/lotto.csv')
df

1   2   3   4   5   6     일     이     삼     사     오     육
0      4   7  17  18  38  44   8.0  12.0  13.0  29.0  33.0  42.0
1      8  12  13  29  33  42   3.0   7.0  14.0  15.0  22.0  38.0
2      3   7  14  15  22  38  21.0  26.0  27.0  32.0  34.0  42.0
3     21  26  27  32  34  42   1.0   9.0  16.0  23.0  24.0  38.0
4      1   9  16  23  24  38  13.0  16.0  23.0  31.0  36.0  44.0
...   ..  ..  ..  ..  ..  ..   ...   ...   ...   ...   ...   ...
1084  10  23  29  33  37  40  11.0  16.0  25.0  27.0  35.0  36.0
1085  11  16  25  27  35  36  13.0  14.0  18.0  21.0  34.0  44.0
1086  13  14  18  21  34  44  11.0  21.0  22.0  30.0  39.0  44.0
1087  11  21  22  30  39  44   4.0  18.0  31.0  37.0  42.0  43.0
1088   4  18  31  37  42  43   NaN   NaN   NaN   NaN   NaN   NaN

[1089 rows x 12 columns]

In [4]:
Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1084  10  23  29  33  37  40
1085  11  16  25  27  35  36
1086  13  14  18  21  34  44
1087  11  21  22  30  39  44
1088   4  18  31  37  42  43

[1089 rows x 6 columns]

In [5]:
Xtest = Xtrain.loc[1088]
Xtest

1     4
2    18
3    31
4    37
5    42
6    43
Name: 1088, dtype: int64

In [6]:
Xtrain.drop(1088, inplace = True)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1083   9  13  21  25  32  42
1084  10  23  29  33  37  40
1085  11  16  25  27  35  36
1086  13  14  18  21  34  44
1087  11  21  22  30  39  44

[1088 rows x 6 columns]

In [7]:
ytrain = df.drop(['1', '2', '3', '4','5', '6'], axis = 1)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1084  11.0  16.0  25.0  27.0  35.0  36.0
1085  13.0  14.0  18.0  21.0  34.0  44.0
1086  11.0  21.0  22.0  30.0  39.0  44.0
1087   4.0  18.0  31.0  37.0  42.0  43.0
1088   NaN   NaN   NaN   NaN   NaN   NaN

[1089 rows x 6 columns]

In [8]:
ytrain.dropna(inplace = True)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1083  10.0  23.0  29.0  33.0  37.0  40.0
1084  11.0  16.0  25.0  27.0  35.0  36.0
1085  13.0  14.0  18.0  21.0  34.0  44.0
1086  11.0  21.0  22.0  30.0  39.0  44.0
1087   4.0  18.0  31.0  37.0  42.0  43.0

[1088 rows x 6 columns]

In [9]:
ytrain =ytrain.astype(int)
ytrain

일   이   삼   사   오   육
0      8  12  13  29  33  42
1      3   7  14  15  22  38
2     21  26  27  32  34  42
3      1   9  16  23  24  38
4     13  16  23  31  36  44
...   ..  ..  ..  ..  ..  ..
1083  10  23  29  33  37  40
1084  11  16  25  27  35  36
1085  13  14  18  21  34  44
1086  11  21  22  30  39  44
1087   4  18  31  37  42  43

[1088 rows x 6 columns]

In [10]:
from pandas import get_dummies

Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)
Xtest

4   18  31  37  42  43
1   1   0   0   0   0   0
2   0   1   0   0   0   0
3   0   0   1   0   0   0
4   0   0   0   1   0   0
5   0   0   0   0   1   0
6   0   0   0   0   0   1

In [11]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.1,
                                        random_state = 202309)


In [12]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202309)

In [13]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

In [27]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 700)
model2 = LogisticRegression(random_state = 202309)
model3 = SVC(random_state = 202309, probability = True)
model4 = DecisionTreeClassifier(random_state = 202309,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 202309,
                                max_depth = 2,
                                n_estimators= 60)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202309)
model8 = LGBMClassifier(random_state = 202309)
model9 = XGBClassifier(random_state = 202309, silent = True, verbosity = 0)


In [28]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[ 1  8 20 31 34 45]
 [ 1  8 20 24 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 27 34 45]
 [ 1 11 17 27 34 45]
 [ 1  8 20 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1 10 20 27 34 45]
 [ 1 10 20 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 31 34 45]
 [ 1 11 17 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 24 34 45]
 [ 1 10 20 24 39 45]
 [ 1  7 20 24 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 24 34 45]
 [ 1  8 15 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1  7 20 27 34 45]
 [ 1 11 17 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1  7 20 24 39 45]
 [ 1  8 20 27 34 45]
 [ 1  8 20 24 34 45]
 [ 1 10 17 27 34 45]
 [ 1  7 15 24 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 31 34 45]
 [ 1  7 20 24 39 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 24 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 27 34 45]
 [ 1  8 20 27 34 45]
 [ 1  8 15 31 34 44]
 [ 1  8 20 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 27 34 45]
 [ 1  8 15 27 34 45]
 [ 1  8 20 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1 1

In [29]:
# 평가용 함수 - 분류
from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

7.773455184445791
8.858555532151275
7.845507489486203


In [17]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(random_state = 202307,
#                               max_depth = 3,
#                               n_estimators= 5)
# model.fit(Xtr, ytr)

# rpred = model.predict(Xval)
# rpred

In [18]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [19]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [20]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))

In [21]:
pred = model1.predict(Xtest)
pred

array([[ 1, 12, 18, 16, 39, 44],
       [ 1, 12, 18, 16, 39, 44],
       [ 1, 12, 18, 16, 39, 44],
       [ 1, 12, 18, 16, 39, 44],
       [ 1, 12, 18, 26, 39, 44],
       [ 1, 12, 18, 16, 39, 44]])

In [22]:
predi = model4.predict(Xtest)
predi

array([[10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41]])

In [23]:
predo = model5.predict(Xtest)
predo

array([[ 1, 17, 27, 33, 39, 43],
       [ 1, 17, 27, 33, 39, 43],
       [ 1, 17, 27, 33, 39, 43],
       [ 1, 17, 27, 33, 39, 43],
       [ 1, 17, 27, 33, 39, 43],
       [ 1, 17, 27, 33, 39, 43]])