<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/1097Lotto2%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/lotto2.csv')
df

1   2   3   4   5   6  보너스     일     이     삼     사     오     육
0     11  21  22  30  39  44   31  13.0  14.0  18.0  21.0  34.0  44.0
1     13  14  18  21  34  44   16  11.0  16.0  25.0  27.0  35.0  36.0
2     11  16  25  27  35  36   37   4.0   7.0  17.0  18.0  38.0  44.0
3      4   7  17  18  38  44   36   8.0  12.0  13.0  29.0  33.0  42.0
4      8  12  13  29  33  42    5   3.0   7.0  14.0  15.0  22.0  38.0
...   ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   ...   ...
1091   7  18  19  26  33  45   37  10.0  17.0  22.0  30.0  35.0  43.0
1092  10  17  22  30  35  43   44   6.0   7.0  15.0  22.0  26.0  40.0
1093   6   7  15  22  26  40   41   8.0  14.0  28.0  29.0  34.0  40.0
1094   8  14  28  29  34  40   12   1.0  12.0  16.0  19.0  23.0  43.0
1095   1  12  16  19  23  43   34   NaN   NaN   NaN   NaN   NaN   NaN

[1096 rows x 13 columns]

In [4]:
Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
Xtrain

1   2   3   4   5   6  보너스
0     11  21  22  30  39  44   31
1     13  14  18  21  34  44   16
2     11  16  25  27  35  36   37
3      4   7  17  18  38  44   36
4      8  12  13  29  33  42    5
...   ..  ..  ..  ..  ..  ..  ...
1091   7  18  19  26  33  45   37
1092  10  17  22  30  35  43   44
1093   6   7  15  22  26  40   41
1094   8  14  28  29  34  40   12
1095   1  12  16  19  23  43   34

[1096 rows x 7 columns]

In [5]:
Xtest = Xtrain.iloc[Xtrain.index[-1]]
Xtest

1       1
2      12
3      16
4      19
5      23
6      43
보너스    34
Name: 1095, dtype: int64

In [6]:
Xtrain.drop(Xtrain.index[-1], inplace = True)
Xtrain

1   2   3   4   5   6  보너스
0     11  21  22  30  39  44   31
1     13  14  18  21  34  44   16
2     11  16  25  27  35  36   37
3      4   7  17  18  38  44   36
4      8  12  13  29  33  42    5
...   ..  ..  ..  ..  ..  ..  ...
1090   6  20  23  24  28  30   44
1091   7  18  19  26  33  45   37
1092  10  17  22  30  35  43   44
1093   6   7  15  22  26  40   41
1094   8  14  28  29  34  40   12

[1095 rows x 7 columns]

In [7]:
ytrain = df.drop(['1', '2', '3', '4','5', '6', '보너스'], axis = 1)
ytrain

일     이     삼     사     오     육
0     13.0  14.0  18.0  21.0  34.0  44.0
1     11.0  16.0  25.0  27.0  35.0  36.0
2      4.0   7.0  17.0  18.0  38.0  44.0
3      8.0  12.0  13.0  29.0  33.0  42.0
4      3.0   7.0  14.0  15.0  22.0  38.0
...    ...   ...   ...   ...   ...   ...
1091  10.0  17.0  22.0  30.0  35.0  43.0
1092   6.0   7.0  15.0  22.0  26.0  40.0
1093   8.0  14.0  28.0  29.0  34.0  40.0
1094   1.0  12.0  16.0  19.0  23.0  43.0
1095   NaN   NaN   NaN   NaN   NaN   NaN

[1096 rows x 6 columns]

In [8]:
ytrain.dropna(inplace = True)
ytrain

일     이     삼     사     오     육
0     13.0  14.0  18.0  21.0  34.0  44.0
1     11.0  16.0  25.0  27.0  35.0  36.0
2      4.0   7.0  17.0  18.0  38.0  44.0
3      8.0  12.0  13.0  29.0  33.0  42.0
4      3.0   7.0  14.0  15.0  22.0  38.0
...    ...   ...   ...   ...   ...   ...
1090   7.0  18.0  19.0  26.0  33.0  45.0
1091  10.0  17.0  22.0  30.0  35.0  43.0
1092   6.0   7.0  15.0  22.0  26.0  40.0
1093   8.0  14.0  28.0  29.0  34.0  40.0
1094   1.0  12.0  16.0  19.0  23.0  43.0

[1095 rows x 6 columns]

In [9]:
ytrain =ytrain.astype(int)
ytrain

일   이   삼   사   오   육
0     13  14  18  21  34  44
1     11  16  25  27  35  36
2      4   7  17  18  38  44
3      8  12  13  29  33  42
4      3   7  14  15  22  38
...   ..  ..  ..  ..  ..  ..
1090   7  18  19  26  33  45
1091  10  17  22  30  35  43
1092   6   7  15  22  26  40
1093   8  14  28  29  34  40
1094   1  12  16  19  23  43

[1095 rows x 6 columns]

In [10]:
from pandas import get_dummies

Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)
Xtest

1   12  16  19  23  34  43
1     1   0   0   0   0   0   0
2     0   1   0   0   0   0   0
3     0   0   1   0   0   0   0
4     0   0   0   1   0   0   0
5     0   0   0   0   1   0   0
6     0   0   0   0   0   0   1
보너스   0   0   0   0   0   1   0

In [11]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.1,
                                        random_state = 202309)


In [12]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202309)

In [13]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3109 sha256=6696fe00fb75e6b3ed03f6de4722dbe0a62204e85ebf8e2a28075dd01ca6a93e
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVC: filename=SVC-0.1-py3-none-any.whl size=1872 sha256=c6535a55f22c3b59e96f6535f6696619c03113c96c45e093dcc61bc5adf76770
  Stored in directory: /root/.cache/pip/wheels/88/51/46/316b33cfa9e39d0749762daa17b6a8646e3050079185747370
Successfully built SVC
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81841 sha256=038c9740c7325fe4a5015e0e2931d5dd439563bd96802c8d19aa65711af51ff1
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce

In [14]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 300,
                              leaf_size = 7)
model2 = LogisticRegression(random_state = 202309)
model3 = SVC(random_state = 202309, probability = True)
model4 = DecisionTreeClassifier(random_state = 202309,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 202309,
                                max_depth = 2,
                                n_estimators= 60)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202309)
model8 = LGBMClassifier(random_state = 202309)
model9 = XGBClassifier(random_state = 202309, silent = True, verbosity = 0)


In [15]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[ 1  8 19 31 34 45]
 [ 1  8 20 33 34 45]
 [ 1 14 19 21 34 45]
 [ 1 14 19 30 34 43]
 [ 1  8 16 23 33 45]
 [ 1 12 19 27 34 44]
 [ 2  8 14 27 34 44]
 [ 2  7 20 27 34 45]
 [ 1 12 13 27 34 45]
 [ 1  8 20 26 33 45]
 [ 1  7 13 27 34 45]
 [ 1  8 20 31 34 45]
 [ 1  7 18 27 34 45]
 [ 1  7 13 27 34 45]
 [ 1 11 15 30 34 43]
 [ 1 11 16 33 36 45]
 [ 1  8 19 33 34 45]
 [ 1  8 20 21 34 45]
 [ 1  7 18 27 34 45]
 [ 1  5 14 27 35 45]
 [ 1  8 16 23 34 45]
 [ 2 13 20 27 34 45]
 [ 1 11 16 32 33 45]
 [ 1 10 20 29 34 45]
 [ 1 11 16 33 33 45]
 [ 1 11 16 30 34 45]
 [ 1  8 16 31 33 45]
 [ 2 12 13 27 34 45]
 [ 1 11 16 31 33 45]
 [ 1 11 16 33 38 45]
 [ 2  7 19 27 34 45]
 [ 1  7 18 27 34 45]
 [ 1  7 18 27 34 45]
 [ 1 11 16 23 34 45]
 [ 1 12 19 21 34 45]
 [ 1  8 19 31 34 45]
 [ 1  8 20 33 34 45]
 [ 2  8 20 30 34 45]
 [ 2  7 20 29 39 45]
 [ 2  8 20 30 34 45]
 [ 1 10 18 26 39 45]
 [ 1 10 18 27 34 45]
 [ 1  8 19 33 34 44]
 [ 1  7 18 27 34 45]
 [ 1 11 16 32 33 45]
 [ 1 10 13 27 38 45]
 [ 1  8 19 31 34 45]
 [ 2 1

In [16]:
# 평가용 함수 - 분류
from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

7.727263814611616
9.141397678427053
7.916897923257109


In [17]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(random_state = 202307,
#                               max_depth = 3,
#                               n_estimators= 5)
# model.fit(Xtr, ytr)

# rpred = model.predict(Xval)
# rpred

In [18]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [19]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [20]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))

In [21]:
pred = model1.predict(Xtest)
pred

array([[ 1, 11, 13, 25, 38, 45],
       [ 1, 11, 13, 25, 38, 45],
       [ 1, 11, 13, 26, 38, 45],
       [ 1, 11, 13, 26, 38, 45],
       [ 1, 11, 13, 25, 38, 45],
       [ 1, 11, 13, 26, 38, 45],
       [ 1, 11, 13, 25, 38, 45]])

In [22]:
from sklearn.neighbors import KNeighborsClassifier

model11 = KNeighborsClassifier(n_neighbors = 300,
                              leaf_size = 7)

model11.fit(Xtrain, ytrain)

kpred = model11.predict(Xtest)
kpred

array([[ 4, 11, 13, 26, 38, 45],
       [ 4, 11, 13, 26, 38, 45],
       [ 4, 11, 13, 26, 38, 45],
       [ 4, 11, 13, 26, 38, 45],
       [ 1, 11, 13, 26, 38, 45],
       [ 4, 11, 13, 26, 38, 45],
       [ 1, 11, 13, 26, 38, 45]])

In [23]:
predi = model4.predict(Xtest)
predi

array([[ 2,  6, 18, 21, 33, 34],
       [ 2,  6, 18, 21, 33, 34],
       [ 2,  6, 18, 21, 33, 34],
       [ 2,  6, 18, 21, 33, 34],
       [ 2,  6, 18, 21, 33, 34],
       [ 2,  6, 18, 21, 33, 34],
       [ 2,  6, 18, 21, 33, 34]])

In [24]:
from sklearn.tree import DecisionTreeClassifier

model44 = DecisionTreeClassifier(random_state = 202311,
                                max_depth = 50)
model44.fit(Xtrain, ytrain)

dpred = model44.predict(Xtest)
dpred

array([[11, 12, 18, 21, 31, 38],
       [11, 12, 18, 21, 31, 38],
       [11, 12, 18, 21, 31, 38],
       [11, 12, 18, 21, 31, 38],
       [11, 12, 18, 21, 31, 38],
       [11, 12, 18, 21, 31, 38],
       [11, 12, 18, 21, 31, 38]])

In [25]:
predo = model5.predict(Xtest)
predo

array([[ 4, 10, 24, 22, 28, 33],
       [ 4, 10, 24, 22, 28, 33],
       [ 4, 10, 24, 22, 28, 33],
       [ 4, 10, 24, 22, 28, 33],
       [ 4, 10, 24, 22, 28, 33],
       [ 4, 10, 24, 22, 28, 33],
       [ 4, 10, 24, 22, 28, 33]])

In [26]:
from sklearn.ensemble import RandomForestRegressor

model55 = RandomForestClassifier(random_state = 202311,
                                max_depth = 2,
                                n_estimators= 60)
model55.fit(Xtrain, ytrain)

rpred = model55.predict(Xtest)
rpred

array([[ 4, 12, 18, 22, 28, 33],
       [ 4, 12, 18, 22, 28, 33],
       [ 4, 12, 18, 22, 28, 33],
       [ 4, 12, 18, 22, 28, 33],
       [ 4, 12, 18, 22, 28, 33],
       [ 4, 12, 18, 22, 28, 33],
       [ 4, 12, 18, 22, 28, 33]])