<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/1103Lotto_%EC%98%88%EC%B8%A1%EC%8B%A4%ED%97%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
win = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/로또/data/jlotto.csv', delimiter = ',')
win

array([[ 4.,  7., 17., ..., 29., 33., 42.],
       [ 8., 12., 13., ..., 15., 22., 38.],
       [ 3.,  7., 14., ..., 32., 34., 42.],
       ...,
       [ 3., 20., 28., ..., 30., 31., 43.],
       [17., 26., 29., ..., 28., 36., 42.],
       [ 6.,  7., 13., ..., 26., 37., 38.]])

In [3]:
xn = len(win)

In [86]:
# 숫자를 원핫 인코딩으로 변환
def n2o(numbers):

  oh = np.zeros(45)  # 45개의 빈 칸 만들기

  for i in range(6):            # 6개의 당첨번호를 반복
      (oh[int(numbers[i])-1] = 1).any()   # 번호는 1부터 시작하고 인덱스는 0부터 시작하니 1을 빼줌
  return oh

# 원핫 인코딩을 숫자로 변환
def o2n(oh):

  numbers = []

  for i in range(len(oh)):
    if oh[i] == 1:           # oh[i]이 1 이면 해당 번호를 출력
      numbers.append(int(i+1))    # 인덱스 보다 숫자가 1크니까 1더해줌 출력

  return numbers

In [34]:
numbers = win[: , :]  # 이게 문제라서 못 하겠음ㅠ 데이터 프레임이 문제인가?
                      # 데이터 프레임으로 안열고 넘파이 텍스트 가져오기 하니 됨
ohs = list(map(n2o, numbers))

xs = ohs[0:xn -1]
ys = ohs[1:xn]

# 원핫 인코딩 확인
print('ohs')
print('x[0] :' + str(xs[0]))
print('y[0] :' + str(ys[0]))

# 번호 확인
print('numbers')
print('x[0] :' + str(o2n(xs[0])))
print('y[0] :' + str(o2n(ys[0])))

ohs
x[0] :[0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
y[0] :[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
numbers
x[0] :[4, 7, 17, 18, 38, 44]
y[0] :[8, 12, 13, 29, 33, 42]


In [35]:
train = (0, int(len(win)*0.7))
val = (int(len(win)*0.6), int(len(win)*0.8))
test = (int(len(win)*0.8), len(win))

print('train : {0}, val : {1}, test : {2}'.format(train, val, test))

train : (0, 770), val : (660, 880), test : (880, 1101)


In [36]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(xs, ys,
                                        test_size = 0.2,
                                        random_state = 20241)

In [37]:
# 교차 검증
# 지표를 하나만 설정할 경우
from sklearn.model_selection import cross_val_score
# 지표를 두개 이상 설정할 경우
from sklearn.model_selection import cross_validate

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold

# KFold 생성
kfold = KFold(n_splits = 10, shuffle = True, random_state = 1)

In [38]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

In [39]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

# 사용할 모델들
model1 = KNeighborsClassifier()
model2 = LogisticRegression(random_state=20241)
model3 = SVC(random_state = 20241, probability = True)
model4 = DecisionTreeClassifier(random_state=20241)
model5 = RandomForestClassifier(random_state=20241)
model6 = AdaBoostClassifier(random_state=20241)
model7 = GradientBoostingClassifier(random_state=20241)
model8 = LGBMClassifier(random_state=20241)
model9 = XGBClassifier(random_state=20241, silent=True, verbosity=0)

model_list1 = [
    ('m1', KNeighborsClassifier()),
    ('m2', LogisticRegression(random_state=20241)),
    ('m3', SVC(random_state = 20241, probability = True)),
    ('m4', DecisionTreeClassifier(random_state=20241)),
    ('m5', RandomForestClassifier(random_state=20241)),
    ('m6',AdaBoostClassifier(random_state=20241)),
    ('m7', GradientBoostingClassifier(random_state=20241)),
    ('m8', LGBMClassifier(random_state=20241)),
    ('m9', XGBClassifier(random_state=20241, silent=True, verbosity=0)),
]

# 배깅 운영 방식은 위에서 사용한 앙상블, 부스팅들이 사용하고 있다
# 보팅 운영 방식도 테스트 해보기 위해 사용
# 매개변수 voting은 투표 방식 설정 (hard(다수결)/soft(확률))
model10 = VotingClassifier(estimators=model_list1, voting='hard')

model_list2 = [
    ('m10', KNeighborsClassifier()),
    ('m20', LogisticRegression(random_state=20241)),
    ('m30', SVC(random_state = 20241, probability = True)),
    ('m40', DecisionTreeClassifier(random_state=20241)),
    ('m50', RandomForestClassifier(random_state=20241)),
    ('m60', AdaBoostClassifier(random_state=20241)),
    ('m70', GradientBoostingClassifier(random_state=20241)),
    ('m80', LGBMClassifier(random_state=20241)),
    ('m90', XGBClassifier(random_state=20241, silent=True, verbosity=0)),
]

model11 = VotingClassifier(estimators=model_list2, voting='soft')

In [45]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
DecisionTree :  [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
RandomForest :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [46]:
# 평가용 함수 - 분류
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

print('F1')
print(f1_score(yval, pred1, average = 'macro'))
print(f1_score(yval, pred4, average = 'macro'))
print(f1_score(yval, pred5, average = 'macro'))
print('=======================================')

print('RAS')
print(roc_auc_score(yval, pred1))
print(roc_auc_score(yval, pred4))
print(roc_auc_score(yval, pred5))
print('=======================================')

print('MSE')
print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

F1
0.034246209396463764
0.14802331967068177
0.0
RAS
0.5000228407800069
0.5099087395511964
0.499942726231386
MSE
0.38455011101128017
0.4760952285695233
0.3652866592613853


In [53]:
xtest = [13, 14, 22, 26, 37, 38]
Xtest = n2o(xtest)

In [70]:
from sklearn.neighbors import KNeighborsClassifier

model11 = KNeighborsClassifier(n_neighbors = xn//6,
                              leaf_size = 6)

model11.fit(xs, ys)

kpred = model11.predict(Xtest.reshape(1, -1))
kpred
# o2n(kpred)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
from sklearn.tree import DecisionTreeClassifier

model44 = DecisionTreeClassifier(random_state = 20241,
                                max_depth = 50)
model44.fit(xs, ys)

ohdpred = model44.predict(Xtest.reshape(1, -1))
ohdpred

dpred = list(map(o2n, ohdpred))
dpred
# dpred = []
# for i in range(len(ohdpred)):
#   if ohdpred[i] == 1:
#     dpred.append(i+1)

# dpred


[[1, 8, 24, 31, 34, 44]]

In [89]:
from sklearn.ensemble import RandomForestRegressor

model55 = RandomForestClassifier(random_state = 20241,
                                max_depth = 2,
                                n_estimators= 60)
model55.fit(xs, ys)

rpred = model55.predict(Xtest.reshape(1, -1))
rpred
# o2n(rpred)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
브레이크

In [63]:
# df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/lotto2.csv')
# df

In [ ]:
# Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
# Xtrain

1   2   3   4   5   6  보너스
0     11  21  22  30  39  44   31
1     13  14  18  21  34  44   16
2     11  16  25  27  35  36   37
3      4   7  17  18  38  44   36
4      8  12  13  29  33  42    5
...   ..  ..  ..  ..  ..  ..  ...
1095   1  12  16  19  23  43   34
1096  14  33  34  35  37  40    4
1097  12  16  21  24  41  43   15
1098   3  20  28  38  40  43    4
1099  17  26  29  30  31  43   12

[1100 rows x 7 columns]

In [ ]:
Xtrain['chatx'] = Xtrain['1'], Xtrain['2'] + Xtrain['3'] + Xtrain['4'] + Xtrain['5'] + Xtrain['6'] + Xtrain['보너스']
Xtrain


ValueError: ignored

In [ ]:
Xtest = Xtrain.iloc[Xtrain.index(-1)]
Xtest

1      10
2      23
3      29
4      33
5      37
6      40
보너스    16
Name: 1082, dtype: int64

In [ ]:
Xtrain.drop(Xtrain.index(-1), inplace = True)
Xtrain

1   2   3   4   5   6  보너스
0      3   7  14  15  22  38   17
1     21  26  27  32  34  42   31
2      1   9  16  23  24  38   17
3     13  16  23  31  36  44   38
4      4   8  18  24  37  45    6
...   ..  ..  ..  ..  ..  ..  ...
1077  14  15  26  27  40  42   34
1078  16  24  29  40  41  42    3
1079  14  27  30  31  40  42    2
1080  11  16  19  21  27  31   30
1081   9  13  21  25  32  42    2

[1082 rows x 7 columns]

In [ ]:
ytrain = df.drop(['1', '2', '3', '4','5', '6', '보너스'], axis = 1)
ytrain

일     이     삼     사     오     육
0     21.0  26.0  27.0  32.0  34.0  42.0
1      1.0   9.0  16.0  23.0  24.0  38.0
2     13.0  16.0  23.0  31.0  36.0  44.0
3      4.0   8.0  18.0  24.0  37.0  45.0
4      6.0  10.0  11.0  14.0  36.0  38.0
...    ...   ...   ...   ...   ...   ...
1078  14.0  27.0  30.0  31.0  40.0  42.0
1079  11.0  16.0  19.0  21.0  27.0  31.0
1080   9.0  13.0  21.0  25.0  32.0  42.0
1081  10.0  23.0  29.0  33.0  37.0  40.0
1082   NaN   NaN   NaN   NaN   NaN   NaN

[1083 rows x 6 columns]

In [ ]:
ytrain.dropna(inplace = True)
ytrain

일     이     삼     사     오     육
0     21.0  26.0  27.0  32.0  34.0  42.0
1      1.0   9.0  16.0  23.0  24.0  38.0
2     13.0  16.0  23.0  31.0  36.0  44.0
3      4.0   8.0  18.0  24.0  37.0  45.0
4      6.0  10.0  11.0  14.0  36.0  38.0
...    ...   ...   ...   ...   ...   ...
1077  16.0  24.0  29.0  40.0  41.0  42.0
1078  14.0  27.0  30.0  31.0  40.0  42.0
1079  11.0  16.0  19.0  21.0  27.0  31.0
1080   9.0  13.0  21.0  25.0  32.0  42.0
1081  10.0  23.0  29.0  33.0  37.0  40.0

[1082 rows x 6 columns]

In [ ]:
ytrain.astype(int)

일   이   삼   사   오   육
0     21  26  27  32  34  42
1      1   9  16  23  24  38
2     13  16  23  31  36  44
3      4   8  18  24  37  45
4      6  10  11  14  36  38
...   ..  ..  ..  ..  ..  ..
1077  16  24  29  40  41  42
1078  14  27  30  31  40  42
1079  11  16  19  21  27  31
1080   9  13  21  25  32  42
1081  10  23  29  33  37  40

[1082 rows x 6 columns]

In [ ]:
from pandas import get_dummies

Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)
Xtest

10  16  23  29  33  37  40
1     1   0   0   0   0   0   0
2     0   0   1   0   0   0   0
3     0   0   0   1   0   0   0
4     0   0   0   0   1   0   0
5     0   0   0   0   0   1   0
6     0   0   0   0   0   0   1
보너스   0   1   0   0   0   0   0

In [ ]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.2,
                                        random_state = 202309)


In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202309)

In [ ]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3111 sha256=6559418ac9e81b4d4ab45903c110809c8fd9076a4141e2576b0c1cd3cf8ae201
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVC: filename=SVC-0.1-py3-none-any.whl size=1870 sha256=a21a26650c63bc0e84eed9836d0461f82fe7d6a2c3b23b3a6fab838ebbc0cb73
  Stored in directory: /root/.cache/pip/wheels/88/51/46/316b33cfa9e39d0749762daa17b6a8646e3050079185747370
Successfully built SVC
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81843 sha256=4dafb0dc4b400bf84162ec18958f9022f3b9c17cb3fa56a5de8fb965bf38b4f3
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce7

In [ ]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier()
model2 = LogisticRegression(random_state = 202309)
model3 = SVC(random_state = 202309, probability = True)
model4 = DecisionTreeClassifier(random_state = 202309)
model5 = RandomForestClassifier(random_state = 202309)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202309)
model8 = LGBMClassifier(random_state = 202309)
model9 = XGBClassifier(random_state = 202309, silent = True, verbosity = 0)

model_list1 = [
    ('m1', KNeighborsClassifier()),
    ('m2', LogisticRegression(random_state = 202309)),
    ('m3', SVC(random_state = 202309, probability = True)),
    ('m4', DecisionTreeClassifier(random_state = 202309)),
    ('m5', RandomForestClassifier(random_state = 202309)),
    ('m6', AdaBoostClassifier(random_state = 202309)),
    ('m7', GradientBoostingClassifier(random_state = 202309)),
    ('m8', LGBMClassifier(random_state = 202309)),
    ('m9', XGBClassifier(random_state = 202309, silent = True, verbosity = 0))
]

# 배깅 운영 방식은 위에서 사용한 앙상블, 부스팅들이 사용하고 있다.
# 보팅 운영 방식도 테스트 해보기 위해 사용
# 매개변수 voting은 투표 방식 설정 (hard(다수결)/soft(확률))

model10 = VotingClassifier(estimators=model_list1, voting='hard')

model_list2 = [
    ('m10', KNeighborsClassifier()),
    ('m20', LogisticRegression(random_state = 202309)),
    ('m30', SVC(random_state = 202309, probability = True)),
    ('m40', DecisionTreeClassifier(random_state = 202309)),
    ('m50', RandomForestClassifier(random_state = 202309)),
    ('m60', AdaBoostClassifier(random_state = 202309)),
    ('m70', GradientBoostingClassifier(random_state = 202309)),
    ('m80', LGBMClassifier(random_state = 202309)),
    ('m90', XGBClassifier(random_state = 202309, silent = True, verbosity = 0))
]

model11 = VotingClassifier(estimators=model_list1, voting='soft')

In [ ]:
# 성능 값을 담을 리스트
score_list = []
# 학습 모델의 이름을 담을 리스트
model_name_list = []
# 최적으로 튜닝된 학습모델을 담을 리스트
best_model_list = []

In [ ]:
# 교차 검증을 수행할 학습 모델 리스트
check_list = [
    model1, model2, model3, model4, model5, model6, model7, model8, model9, model10, model11
]
# 모델 이름
check_name_list = [
    'KNN (Basic)', 'LogisticRegression (Basic)', 'SVM (Basic)', 'DecisionTree (Basic)', 'RandomForest (Basic)', 'AdaBoost (Basic)', 'GradientBoost (Basic)', 'LGBM (Basic)', 'XGBoost (Basic)', 'Voting (hard) (Basic)', 'Voting (soft) (Basic)'
]

In [43]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
DecisionTree :  [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
RandomForest :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [44]:
# 평가용 함수 - 분류
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

print('F1')
print(f1_score(yval, pred1, average = 'macro'))
print(f1_score(yval, pred4, average = 'macro'))
print(f1_score(yval, pred5, average = 'macro'))
print('=======================================')

print('RAS')
print(roc_auc_score(yval, pred1))
print(roc_auc_score(yval, pred4))
print(roc_auc_score(yval, pred5))
print('=======================================')

print('MSE')
print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))


F1
0.034246209396463764
0.14802331967068177
0.0
RAS
0.5000228407800069
0.5099087395511964
0.499942726231386
MSE
0.38455011101128017
0.4760952285695233
0.3652866592613853


In [ ]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(random_state = 202307,
#                               max_depth = 3,
#                               n_estimators= 5)
# model.fit(Xtr, ytr)

# rpred = model.predict(Xval)
# rpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [ ]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [ ]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))

In [ ]:
# from xgboost import XGBRegressor

# xmodel = XGBRegressor(random_state = 6,
#                       max_depth = 5,
#                       n_estimators = 200)
# xmodel.fit(Xtr, ytr)

# xpred = xmodel.predict(Xval)
# xpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, xpred)))

In [ ]:
pred = model.predict(Xtest)
pred

In [ ]:
pred2 = model2.predict(Xtest)
pred2