<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/1103%ED%9A%8CLotto%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [14]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [15]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/lotto.csv')
df

1   2   3   4   5   6     일     이     삼     사     오     육
0      4   7  17  18  38  44   8.0  12.0  13.0  29.0  33.0  42.0
1      8  12  13  29  33  42   3.0   7.0  14.0  15.0  22.0  38.0
2      3   7  14  15  22  38  21.0  26.0  27.0  32.0  34.0  42.0
3     21  26  27  32  34  42   1.0   9.0  16.0  23.0  24.0  38.0
4      1   9  16  23  24  38  13.0  16.0  23.0  31.0  36.0  44.0
...   ..  ..  ..  ..  ..  ..   ...   ...   ...   ...   ...   ...
1097  12  16  21  24  41  43   3.0  20.0  28.0  38.0  40.0  43.0
1098   3  20  28  38  40  43  17.0  26.0  29.0  30.0  31.0  43.0
1099  17  26  29  30  31  43   6.0   7.0  13.0  28.0  36.0  42.0
1100   6   7  13  28  36  42  13.0  14.0  22.0  26.0  37.0  38.0
1101  13  14  22  26  37  38   NaN   NaN   NaN   NaN   NaN   NaN

[1102 rows x 12 columns]

In [17]:
Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1097  12  16  21  24  41  43
1098   3  20  28  38  40  43
1099  17  26  29  30  31  43
1100   6   7  13  28  36  42
1101  13  14  22  26  37  38

[1102 rows x 6 columns]

In [18]:
Xtest = Xtrain.iloc[Xtrain.index[-1]]
Xtest

1    13
2    14
3    22
4    26
5    37
6    38
Name: 1101, dtype: int64

In [19]:
Xtrain.drop(Xtrain.index[-1], inplace = True)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1096  14  33  34  35  37  40
1097  12  16  21  24  41  43
1098   3  20  28  38  40  43
1099  17  26  29  30  31  43
1100   6   7  13  28  36  42

[1101 rows x 6 columns]

In [20]:
ytrain = df.drop(['1', '2', '3', '4','5', '6'], axis = 1)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1097   3.0  20.0  28.0  38.0  40.0  43.0
1098  17.0  26.0  29.0  30.0  31.0  43.0
1099   6.0   7.0  13.0  28.0  36.0  42.0
1100  13.0  14.0  22.0  26.0  37.0  38.0
1101   NaN   NaN   NaN   NaN   NaN   NaN

[1102 rows x 6 columns]

In [21]:
ytrain.dropna(inplace = True)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1096  12.0  16.0  21.0  24.0  41.0  43.0
1097   3.0  20.0  28.0  38.0  40.0  43.0
1098  17.0  26.0  29.0  30.0  31.0  43.0
1099   6.0   7.0  13.0  28.0  36.0  42.0
1100  13.0  14.0  22.0  26.0  37.0  38.0

[1101 rows x 6 columns]

In [22]:
ytrain =ytrain.astype(int)
ytrain

일   이   삼   사   오   육
0      8  12  13  29  33  42
1      3   7  14  15  22  38
2     21  26  27  32  34  42
3      1   9  16  23  24  38
4     13  16  23  31  36  44
...   ..  ..  ..  ..  ..  ..
1096  12  16  21  24  41  43
1097   3  20  28  38  40  43
1098  17  26  29  30  31  43
1099   6   7  13  28  36  42
1100  13  14  22  26  37  38

[1101 rows x 6 columns]

In [23]:
from pandas import get_dummies

Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)
Xtest

13  14  22  26  37  38
1   1   0   0   0   0   0
2   0   1   0   0   0   0
3   0   0   1   0   0   0
4   0   0   0   1   0   0
5   0   0   0   0   1   0
6   0   0   0   0   0   1

In [24]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.1,
                                        random_state = 202311)


In [25]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202311)

In [26]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3109 sha256=0093296af6f0d70a170ab806a59013442fcb09db726e6362e56aa217efa7fb40
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVC: filename=SVC-0.1-py3-none-any.whl size=1872 sha256=6d289c7917068a29913323e9683035be472875f71e278e9b3c115c565b5f2b77
  Stored in directory: /root/.cache/pip/wheels/88/51/46/316b33cfa9e39d0749762daa17b6a8646e3050079185747370
Successfully built SVC
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81841 sha256=b34300cdd8b4b85e5cae47a34429ef9411ac9e4d93cccb8590552da58ee87d16
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce

In [27]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 350,
                              leaf_size = 6)
model2 = LogisticRegression(random_state = 202311)
model3 = SVC(random_state = 202311, probability = True)
model4 = DecisionTreeClassifier(random_state = 202311,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 202311,
                                max_depth = 2,
                                n_estimators= 60)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202311)
model8 = LGBMClassifier(random_state = 202311)
model9 = XGBClassifier(random_state = 202311, silent = True, verbosity = 0)


In [28]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[ 1  8 13 31 34 45]
 [ 1 14 20 31 34 45]
 [ 1 10 18 26 33 45]
 [ 1  8 20 31 34 45]
 [ 1  7 17 27 38 45]
 [ 1  8 20 31 34 45]
 [ 2  8 14 27 34 44]
 [ 1  8 20 31 34 45]
 [ 1 10 20 26 34 45]
 [ 2  7 18 27 38 45]
 [ 1  7 13 27 34 45]
 [ 1 14 20 23 34 45]
 [ 1  7 19 26 34 45]
 [ 2 14 20 26 34 45]
 [ 1  7 13 26 33 45]
 [ 1  4 14 27 34 45]
 [ 1 10 18 26 39 45]
 [ 2  7 14 30 34 44]
 [ 1 10 13 26 38 45]
 [ 1  8 20 31 34 45]
 [ 1  8 20 30 34 45]
 [ 1  8 20 24 34 45]
 [ 2 10 13 26 38 45]
 [ 1 14 20 24 34 45]
 [ 2 14 15 31 34 45]
 [ 2 10 14 24 34 45]
 [ 2  7 14 27 34 45]
 [ 1  8 15 27 34 45]
 [ 1 10 18 26 38 45]
 [ 2  8 20 31 34 45]
 [ 1 14 15 30 34 45]
 [ 1 10 20 24 34 45]
 [ 2 10 18 26 34 45]
 [ 1  8 20 31 34 45]
 [ 1 14 20 31 34 45]
 [ 1  5 19 27 34 45]
 [ 2 10 18 26 38 45]
 [ 1 10 15 26 39 45]
 [ 1  8 20 31 34 45]
 [ 1 10 19 26 34 45]
 [ 1  8 15 30 34 45]
 [ 1 14 20 31 34 45]
 [ 1  8 20 28 34 45]
 [ 1 10 18 26 39 45]
 [ 1  7 14 27 34 45]
 [ 2  7 18 26 39 45]
 [ 2  7 18 26 33 45]
 [ 1  

In [29]:
# from sklearn.linear_model import SGDClassifier

# smodel = SGDClassifier(random_state = 202311)

# smodel.fit(Xtr, ytr)

# spred = smodel.predict(Xval)

# print('SGD : ', + spred)

In [30]:
# from sklearn.metrics import roc_auc_score

# print(np.sqrt(roc_auc_score(yval, pred1, multi_class="ovo")))
# print(np.sqrt(roc_auc_score(yval, pred4, multi_class="ovo")))
# print(np.sqrt(roc_auc_score(yval, pred5, multi_class="ovo")))

# print(roc_auc_score(yval, pred1, multi_class="ovo"))
# print(roc_auc_score(yval, pred4, multi_class="ovo"))
# print(roc_auc_score(yval, pred5, multi_class="ovo"))


In [31]:
# 평가용 함수 - 분류
# from sklearn.metrics import f1_score

# print(np.sqrt(f1_score(yval, pred1, average = 'macro')))
# print(np.sqrt(f1_score(yval, pred4, average = 'macro')))
# print(np.sqrt(f1_score(yval, pred5, average = 'macro')))

In [32]:
# 평가용 함수 - 분류
from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

7.735880288877526
9.191081327894775
7.683881964348623


In [33]:
pred = model1.predict(Xtest)
pred

array([[ 2, 10, 18, 26, 38, 45],
       [ 2, 10, 18, 26, 38, 45],
       [ 1, 10, 18, 26, 38, 45],
       [ 2, 10, 18, 26, 38, 45],
       [ 2, 10, 18, 26, 38, 45],
       [ 1, 10, 18, 26, 38, 45]])

In [34]:
from sklearn.neighbors import KNeighborsClassifier

model11 = KNeighborsClassifier(n_neighbors = 350,
                              leaf_size = 6)

model11.fit(Xtrain, ytrain)

kpred = model11.predict(Xtest)
kpred

array([[ 1, 10, 13, 26, 39, 45],
       [ 1, 10, 13, 26, 39, 45],
       [ 1, 10, 13, 26, 39, 45],
       [ 1, 10, 13, 26, 39, 45],
       [ 1, 10, 13, 26, 39, 45],
       [ 1, 10, 13, 26, 39, 45]])

In [35]:
predi = model4.predict(Xtest)
predi

array([[10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41]])

In [36]:
from sklearn.tree import DecisionTreeClassifier

model44 = DecisionTreeClassifier(random_state = 202311,
                                max_depth = 50)
model44.fit(Xtrain, ytrain)

dpred = model44.predict(Xtest)
dpred

array([[10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41]])

In [37]:
predo = model5.predict(Xtest)
predo

array([[ 1, 12, 18, 21, 34, 41],
       [ 1, 12, 18, 21, 34, 41],
       [ 1, 12, 18, 21, 34, 41],
       [ 1, 12, 18, 21, 34, 41],
       [ 1, 12, 18, 21, 34, 41],
       [ 1, 12, 18, 21, 34, 41]])

In [38]:
from sklearn.ensemble import RandomForestRegressor

model55 = RandomForestClassifier(random_state = 202311,
                                max_depth = 2,
                                n_estimators= 60)
model55.fit(Xtrain, ytrain)

rpred = model55.predict(Xtest)
rpred

array([[ 4, 12, 18, 21, 31, 38],
       [ 4, 12, 18, 21, 31, 38],
       [ 4, 12, 18, 21, 31, 38],
       [ 4, 12, 18, 21, 31, 38],
       [ 4, 12, 18, 21, 31, 38],
       [ 4, 12, 18, 21, 31, 38]])

In [39]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [40]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [41]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))