<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/200Pension%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/pension.csv')
df

win   pension
0    103633  437803.0
1    437803  966616.0
2    966616  113393.0
3    113393  531307.0
4    531307  461102.0
..      ...       ...
194  754655  124420.0
195  124420  544955.0
196  544955  450558.0
197  450558  162132.0
198  162132       NaN

[199 rows x 2 columns]

In [4]:
Xtrain = df.drop('pension', axis = 1)
Xtrain

win
0    103633
1    437803
2    966616
3    113393
4    531307
..      ...
194  754655
195  124420
196  544955
197  450558
198  162132

[199 rows x 1 columns]

In [5]:
Xtest = np.array(Xtrain.iloc[-1])
Xtest

array([162132])

In [6]:
Xtrain.drop(Xtrain.index[-1], inplace = True)
Xtrain

win
0    103633
1    437803
2    966616
3    113393
4    531307
..      ...
193  193202
194  754655
195  124420
196  544955
197  450558

[198 rows x 1 columns]

In [7]:
ytrain = df.drop('win', axis = 1)
ytrain

pension
0    437803.0
1    966616.0
2    113393.0
3    531307.0
4    461102.0
..        ...
194  124420.0
195  544955.0
196  450558.0
197  162132.0
198       NaN

[199 rows x 1 columns]

In [8]:
ytrain.dropna(inplace = True)
ytrain

pension
0    437803.0
1    966616.0
2    113393.0
3    531307.0
4    461102.0
..        ...
193  754655.0
194  124420.0
195  544955.0
196  450558.0
197  162132.0

[198 rows x 1 columns]

In [9]:
ytrain =ytrain.astype('int64')
ytrain

pension
0     437803
1     966616
2     113393
3     531307
4     461102
..       ...
193   754655
194   124420
195   544955
196   450558
197   162132

[198 rows x 1 columns]

In [10]:
# from pandas import get_dummies

# Xtrain = pd.get_dummies(Xtrain)
# Xtest = pd.get_dummies(Xtest)
# Xtest

In [11]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.3,
                                        random_state = 20242)


In [12]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 20242)

In [13]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

In [14]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 6)
model2 = LogisticRegression(random_state = 20242)
model3 = SVC(random_state = 20242, probability = True)
model4 = DecisionTreeClassifier(random_state = 20242,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 20242,
                                max_depth = 2,
                                n_estimators= 5)
model6 = AdaBoostClassifier(random_state = 20242)
model7 = GradientBoostingClassifier(random_state = 20242)
model8 = LGBMClassifier(random_state = 20242)
# model9 = XGBClassifier(random_state = 20242, silent = True, verbosity = 0)

model_list1 = [
    ('m1', KNeighborsClassifier()),
    ('m2', LogisticRegression(random_state = 20242)),
    ('m3', SVC(random_state = 20242, probability = True)),
    ('m4', DecisionTreeClassifier(random_state = 20242)),
    ('m5', RandomForestClassifier(random_state = 20242)),
    ('m6', AdaBoostClassifier(random_state = 20242)),
    ('m7', GradientBoostingClassifier(random_state = 20242)),
    ('m8', LGBMClassifier(random_state = 20242))
    # ('m9', XGBClassifier(random_state = 20242, silent = True, verbosity = 0))
]

# 배깅 운영 방식은 위에서 사용한 앙상블, 부스팅들이 사용하고 있다.
# 보팅 운영 방식도 테스트 해보기 위해 사용
# 매개변수 voting은 투표 방식 설정 (hard(다수결)/soft(확률))

model10 = VotingClassifier(estimators=model_list1, voting='hard')

model_list2 = [
    ('m10', KNeighborsClassifier()),
    ('m20', LogisticRegression(random_state = 20242)),
    ('m30', SVC(random_state = 20242, probability = True)),
    ('m40', DecisionTreeClassifier(random_state = 20242)),
    ('m50', RandomForestClassifier(random_state = 20242)),
    ('m60', AdaBoostClassifier(random_state = 20242)),
    ('m70', GradientBoostingClassifier(random_state = 20242)),
    ('m80', LGBMClassifier(random_state = 20242))
    # ('m90', XGBClassifier(random_state = 20242, silent = True, verbosity = 0))
]

model11 = VotingClassifier(estimators=model_list1, voting='soft')

In [17]:
model1.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)

model2.fit(Xtr, ytr)
model3.fit(Xtr, ytr)
model6.fit(Xtr, ytr)
model7.fit(Xtr, ytr)
model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
model10.fit(Xtr, ytr)
model11.fit(Xtr, ytr)


pred1 = model1.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)

pred2 = model2.predict(Xval)
pred3 = model3.predict(Xval)
pred6 = model6.predict(Xval)
pred7 = model7.predict(Xval)
pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
pred10 = model10.predict(Xval)
pred11 = model11.predict(Xval)

print('KNN : ', pred1)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)

# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

In [18]:
# 평가용 함수 - 분류
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

print('RAS')
# print(roc_auc_score(yval, pred1, multi_class="ovo"))
# print(roc_auc_score(yval, pred2, multi_class="ovo"))
# print(roc_auc_score(yval, pred3, multi_class="ovo"))
# print(roc_auc_score(yval, pred4, multi_class="ovo"))
# print(roc_auc_score(yval, pred5, multi_class="ovo"))
# print(roc_auc_score(yval, pred6, multi_class="ovo"))
# print(roc_auc_score(yval, pred7, multi_class="ovo"))
# print(roc_auc_score(yval, pred8, multi_class="ovo"))
# print(roc_auc_score(yval, pred9, multi_class="ovo"))
# print(roc_auc_score(yval, pred10, multi_class="ovo"))
# print(roc_auc_score(yval, pred11, multi_class="ovo"))

print('=======================================')

print('F1')
print(f1_score(yval, pred1, average = 'macro'))
print(f1_score(yval, pred2, average = 'macro'))
print(f1_score(yval, pred3, average = 'macro'))
print(f1_score(yval, pred4, average = 'macro'))
print(f1_score(yval, pred5, average = 'macro'))
print(f1_score(yval, pred6, average = 'macro'))
print(f1_score(yval, pred7, average = 'macro'))
print(f1_score(yval, pred8, average = 'macro'))
# print(f1_score(yval, pred9, average = 'macro'))
print(f1_score(yval, pred10, average = 'macro'))
print(f1_score(yval, pred11, average = 'macro'))
print('=======================================')

# 낮을수록 좋음
print('MSE')
print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred2)))
print(np.sqrt(mean_squared_error(yval, pred3)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))
print(np.sqrt(mean_squared_error(yval, pred6)))
print(np.sqrt(mean_squared_error(yval, pred7)))
print(np.sqrt(mean_squared_error(yval, pred8)))
# print(np.sqrt(mean_squared_error(yval, pred9)))
print(np.sqrt(mean_squared_error(yval, pred10)))
print(np.sqrt(mean_squared_error(yval, pred11)))

RAS
F1
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
MSE
513477.66891876614
280673.1090094846
404925.66834796977
555924.9039712559
374702.30724142864
587276.7504078606
404925.66834796977
469532.09803203726
404925.66834796977
404925.66834796977


In [19]:
pred1 = model1.predict(Xtest.reshape(1,-1))
pred2 = model2.predict(Xtest.reshape(1,-1))
pred3 = model3.predict(Xtest.reshape(1,-1))
pred4 = model4.predict(Xtest.reshape(1,-1))
pred5 = model5.predict(Xtest.reshape(1,-1))
pred6 = model6.predict(Xtest.reshape(1,-1))
pred7 = model7.predict(Xtest.reshape(1,-1))
pred8 = model8.predict(Xtest.reshape(1,-1))
# pred9 = model9.predict(Xtest.reshape(1,-1))
pred10 = model10.predict(Xtest.reshape(1,-1))
pred11 = model11.predict(Xtest.reshape(1,-1))



print(pred1)
print(pred2)
print(pred3)
print(pred4)
print(pred5)
print(pred6)
print(pred7)
print(pred8)
# print(pred9)
print(pred10)
print(pred11)

[248672]
[550104]
[605195]
[605195]
[307695]
[605195]
[605195]
[487381]
[605195]
[605195]


In [20]:
from sklearn.neighbors import KNeighborsClassifier

model110 = KNeighborsClassifier(n_neighbors = 6)

model110.fit(Xtrain, ytrain)

pred110 = model110.predict(Xtest.reshape(1, -1))
pred110

array([248672])

In [21]:
from sklearn.linear_model import LogisticRegression

model22 = LogisticRegression(random_state = 20242)

model22.fit(Xtrain, ytrain)

pred22 = model22.predict(Xtest.reshape(1, -1))
pred22

array([550104])

In [22]:
from sklearn.svm import SVC

model33 = SVC(random_state = 20242, probability = True)

model33.fit(Xtrain, ytrain)

pred33 = model33.predict(Xtest.reshape(1, -1))
pred33

array([605195])

In [23]:
from sklearn.tree import DecisionTreeClassifier

model44 = DecisionTreeClassifier(random_state = 20242,
                                max_depth = 50)

model44.fit(Xtrain, ytrain)

pred44 = model44.predict(Xtest.reshape(1, -1))
pred44

array([605195])

In [24]:
from sklearn.ensemble import RandomForestClassifier

model55 = RandomForestClassifier(random_state = 20242,
                                max_depth = 2,
                                n_estimators= 60)

model55.fit(Xtrain, ytrain)

pred55 = model55.predict(Xtest.reshape(1, -1))
pred55

array([605195])

In [25]:
from sklearn.ensemble import AdaBoostClassifier

model66 = AdaBoostClassifier(random_state = 20242)

model66.fit(Xtrain, ytrain)

pred66 = model66.predict(Xtest.reshape(1, -1))
pred66

array([689922])

In [26]:
from sklearn.ensemble import GradientBoostingClassifier

model77 = GradientBoostingClassifier(random_state = 20242)

model77.fit(Xtrain, ytrain)

pred77 = model77.predict(Xtest.reshape(1, -1))
pred77

array([605195])

In [27]:
from lightgbm import LGBMClassifier

model88 = LGBMClassifier(random_state = 20242)

model88.fit(Xtrain, ytrain)

pred88 = model88.predict(Xtest.reshape(1, -1))
pred88

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

array([248672])

In [28]:
# from xgboost import XGBClassifier

# model99 = XGBClassifier(random_state = 20242, silent = True, verbosity = 0)

# model99.fit(Xtrain, ytrain)

# pred99 = model99.predict(Xtest.reshape(1, -1))
# pred99

In [29]:
from sklearn.ensemble import VotingClassifier

model100 = VotingClassifier(estimators=model_list1, voting='hard')

model100.fit(Xtrain, ytrain)

pred100 = model100.predict(Xtest.reshape(1, -1))
pred100

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

array([605195])

In [30]:
from sklearn.ensemble import VotingClassifier

model111 = VotingClassifier(estimators=model_list1, voting='soft')

model111.fit(Xtrain, ytrain)

pred111 = model111.predict(Xtest.reshape(1, -1))
pred111

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

array([605195])