<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/Lotto1088%E3%85%87%E3%85%96%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/lotto.csv')
df

1   2   3   4   5   6     일     이     삼     사     오     육
0      4   7  17  18  38  44   8.0  12.0  13.0  29.0  33.0  42.0
1      8  12  13  29  33  42   3.0   7.0  14.0  15.0  22.0  38.0
2      3   7  14  15  22  38  21.0  26.0  27.0  32.0  34.0  42.0
3     21  26  27  32  34  42   1.0   9.0  16.0  23.0  24.0  38.0
4      1   9  16  23  24  38  13.0  16.0  23.0  31.0  36.0  44.0
...   ..  ..  ..  ..  ..  ..   ...   ...   ...   ...   ...   ...
1082  11  16  19  21  27  31   9.0  13.0  21.0  25.0  32.0  42.0
1083   9  13  21  25  32  42  10.0  23.0  29.0  33.0  37.0  40.0
1084  10  23  29  33  37  40  11.0  16.0  25.0  27.0  35.0  36.0
1085  11  16  25  27  35  36  13.0  14.0  18.0  21.0  34.0  44.0
1086  13  14  18  21  34  44   NaN   NaN   NaN   NaN   NaN   NaN

[1087 rows x 12 columns]

In [3]:
Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1082  11  16  19  21  27  31
1083   9  13  21  25  32  42
1084  10  23  29  33  37  40
1085  11  16  25  27  35  36
1086  13  14  18  21  34  44

[1087 rows x 6 columns]

In [4]:
Xtest = Xtrain.loc[1086]
Xtest

1    13
2    14
3    18
4    21
5    34
6    44
Name: 1086, dtype: int64

In [5]:
Xtrain.drop(1086, inplace = True)
Xtrain

1   2   3   4   5   6
0      4   7  17  18  38  44
1      8  12  13  29  33  42
2      3   7  14  15  22  38
3     21  26  27  32  34  42
4      1   9  16  23  24  38
...   ..  ..  ..  ..  ..  ..
1081  14  27  30  31  40  42
1082  11  16  19  21  27  31
1083   9  13  21  25  32  42
1084  10  23  29  33  37  40
1085  11  16  25  27  35  36

[1086 rows x 6 columns]

In [6]:
ytrain = df.drop(['1', '2', '3', '4','5', '6'], axis = 1)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1082   9.0  13.0  21.0  25.0  32.0  42.0
1083  10.0  23.0  29.0  33.0  37.0  40.0
1084  11.0  16.0  25.0  27.0  35.0  36.0
1085  13.0  14.0  18.0  21.0  34.0  44.0
1086   NaN   NaN   NaN   NaN   NaN   NaN

[1087 rows x 6 columns]

In [7]:
ytrain.dropna(inplace = True)
ytrain

일     이     삼     사     오     육
0      8.0  12.0  13.0  29.0  33.0  42.0
1      3.0   7.0  14.0  15.0  22.0  38.0
2     21.0  26.0  27.0  32.0  34.0  42.0
3      1.0   9.0  16.0  23.0  24.0  38.0
4     13.0  16.0  23.0  31.0  36.0  44.0
...    ...   ...   ...   ...   ...   ...
1081  11.0  16.0  19.0  21.0  27.0  31.0
1082   9.0  13.0  21.0  25.0  32.0  42.0
1083  10.0  23.0  29.0  33.0  37.0  40.0
1084  11.0  16.0  25.0  27.0  35.0  36.0
1085  13.0  14.0  18.0  21.0  34.0  44.0

[1086 rows x 6 columns]

In [8]:
ytrain =ytrain.astype(int)
ytrain

일   이   삼   사   오   육
0      8  12  13  29  33  42
1      3   7  14  15  22  38
2     21  26  27  32  34  42
3      1   9  16  23  24  38
4     13  16  23  31  36  44
...   ..  ..  ..  ..  ..  ..
1081  11  16  19  21  27  31
1082   9  13  21  25  32  42
1083  10  23  29  33  37  40
1084  11  16  25  27  35  36
1085  13  14  18  21  34  44

[1086 rows x 6 columns]

In [9]:
from pandas import get_dummies

Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)
Xtest

13  14  18  21  34  44
1   1   0   0   0   0   0
2   0   1   0   0   0   0
3   0   0   1   0   0   0
4   0   0   0   1   0   0
5   0   0   0   0   1   0
6   0   0   0   0   0   1

In [10]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.2,
                                        random_state = 202309)


In [11]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202309)

In [12]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3111 sha256=3323965fe89668da81dfb1b006f3d720d50b20f49072ecec17a3785b940bab5b
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVC: filename=SVC-0.1-py3-none-any.whl size=1870 sha256=4a6cdf789d78947ff8ad341e11254bd4dccb6c26fb3656323c4a348d21da69ca
  Stored in directory: /root/.cache/pip/wheels/88/51/46/316b33cfa9e39d0749762daa17b6a8646e3050079185747370
Successfully built SVC
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81843 sha256=cb60fb75146bb03630f09fd9273d2d4523a903d0e888b091e41be4529e93f9b3
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce7

In [13]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 100)
model2 = LogisticRegression(random_state = 202309)
model3 = SVC(random_state = 202309, probability = True)
model4 = DecisionTreeClassifier(random_state = 202309,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 202309,
                                max_depth = 2,
                                n_estimators= 5)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202309)
model8 = LGBMClassifier(random_state = 202309)
model9 = XGBClassifier(random_state = 202309, silent = True, verbosity = 0)


In [14]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[ 2  7 18 21 38 45]
 [ 1  8 20 27 34 44]
 [ 1 11 16 18 34 43]
 ...
 [ 1 12 20 21 39 45]
 [ 1 10 20 26 38 45]
 [ 1 12 19 31 34 43]]
DecisionTree :  [[ 8 11 19 21 36 45]
 [16 17 22 31 34 37]
 [ 2  9 15 23 34 40]
 ...
 [ 5  6 19 26 41 45]
 [ 1  3  8 21 22 31]
 [14 15 16 17 38 45]]
RandomForest :  [[ 1 11 13 21 37 45]
 [ 1 11 15 31 34 45]
 [ 1 11 15 31 34 45]
 ...
 [ 3  7 15 24 37 45]
 [ 1 11 13 21 37 45]
 [ 1 11 15 31 34 45]]


In [15]:
# 평가용 함수 - 분류
from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

8.398066618917703
9.346498469434621
8.270235123067886


In [ ]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(random_state = 202307,
#                               max_depth = 3,
#                               n_estimators= 5)
# model.fit(Xtr, ytr)

# rpred = model.predict(Xval)
# rpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [ ]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [ ]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))

In [16]:
pred = model1.predict(Xtest)
pred

array([[ 1, 11, 13, 26, 36, 45],
       [ 1, 10, 13, 26, 34, 45],
       [ 1, 11, 13, 21, 36, 45],
       [ 1, 10, 13, 26, 34, 45],
       [ 1, 10, 13, 26, 34, 45],
       [ 1, 11, 18, 26, 36, 45]])

In [17]:
predi = model4.predict(Xtest)
predi

array([[10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41],
       [10, 15, 18, 21, 34, 41]])

In [18]:
predo = model5.predict(Xtest)
predo

array([[ 7, 22, 29, 33, 34, 35],
       [ 7, 22, 29, 33, 34, 35],
       [ 7, 22, 29, 33, 34, 35],
       [ 7, 22, 29, 33, 34, 35],
       [ 7, 22, 29, 33, 34, 35],
       [ 7, 22, 29, 33, 34, 35]])