<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/Lotto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/lotto.csv')
df

1   2   3   4   5   6  보너스     일     이     삼     사     오     육
0      3   7  14  15  22  38   17  21.0  26.0  27.0  32.0  34.0  42.0
1     21  26  27  32  34  42   31   1.0   9.0  16.0  23.0  24.0  38.0
2      1   9  16  23  24  38   17  13.0  16.0  23.0  31.0  36.0  44.0
3     13  16  23  31  36  44   38   4.0   8.0  18.0  24.0  37.0  45.0
4      4   8  18  24  37  45    6   6.0  10.0  11.0  14.0  36.0  38.0
...   ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   ...   ...
1078  16  24  29  40  41  42    3  14.0  27.0  30.0  31.0  40.0  42.0
1079  14  27  30  31  40  42    2  11.0  16.0  19.0  21.0  27.0  31.0
1080  11  16  19  21  27  31   30   9.0  13.0  21.0  25.0  32.0  42.0
1081   9  13  21  25  32  42    2  10.0  23.0  29.0  33.0  37.0  40.0
1082  10  23  29  33  37  40   16   NaN   NaN   NaN   NaN   NaN   NaN

[1083 rows x 13 columns]

In [4]:
Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
Xtrain

1   2   3   4   5   6  보너스
0      3   7  14  15  22  38   17
1     21  26  27  32  34  42   31
2      1   9  16  23  24  38   17
3     13  16  23  31  36  44   38
4      4   8  18  24  37  45    6
...   ..  ..  ..  ..  ..  ..  ...
1078  16  24  29  40  41  42    3
1079  14  27  30  31  40  42    2
1080  11  16  19  21  27  31   30
1081   9  13  21  25  32  42    2
1082  10  23  29  33  37  40   16

[1083 rows x 7 columns]

In [5]:
Xtest = Xtrain.loc[1082]
Xtest

1      10
2      23
3      29
4      33
5      37
6      40
보너스    16
Name: 1082, dtype: int64

In [6]:
Xtrain.drop(1082, inplace = True)
Xtrain

1   2   3   4   5   6  보너스
0      3   7  14  15  22  38   17
1     21  26  27  32  34  42   31
2      1   9  16  23  24  38   17
3     13  16  23  31  36  44   38
4      4   8  18  24  37  45    6
...   ..  ..  ..  ..  ..  ..  ...
1077  14  15  26  27  40  42   34
1078  16  24  29  40  41  42    3
1079  14  27  30  31  40  42    2
1080  11  16  19  21  27  31   30
1081   9  13  21  25  32  42    2

[1082 rows x 7 columns]

In [7]:
ytrain = df.drop(['1', '2', '3', '4','5', '6', '보너스'], axis = 1)
ytrain

일     이     삼     사     오     육
0     21.0  26.0  27.0  32.0  34.0  42.0
1      1.0   9.0  16.0  23.0  24.0  38.0
2     13.0  16.0  23.0  31.0  36.0  44.0
3      4.0   8.0  18.0  24.0  37.0  45.0
4      6.0  10.0  11.0  14.0  36.0  38.0
...    ...   ...   ...   ...   ...   ...
1078  14.0  27.0  30.0  31.0  40.0  42.0
1079  11.0  16.0  19.0  21.0  27.0  31.0
1080   9.0  13.0  21.0  25.0  32.0  42.0
1081  10.0  23.0  29.0  33.0  37.0  40.0
1082   NaN   NaN   NaN   NaN   NaN   NaN

[1083 rows x 6 columns]

In [8]:
ytrain.dropna(inplace = True)
ytrain

일     이     삼     사     오     육
0     21.0  26.0  27.0  32.0  34.0  42.0
1      1.0   9.0  16.0  23.0  24.0  38.0
2     13.0  16.0  23.0  31.0  36.0  44.0
3      4.0   8.0  18.0  24.0  37.0  45.0
4      6.0  10.0  11.0  14.0  36.0  38.0
...    ...   ...   ...   ...   ...   ...
1077  16.0  24.0  29.0  40.0  41.0  42.0
1078  14.0  27.0  30.0  31.0  40.0  42.0
1079  11.0  16.0  19.0  21.0  27.0  31.0
1080   9.0  13.0  21.0  25.0  32.0  42.0
1081  10.0  23.0  29.0  33.0  37.0  40.0

[1082 rows x 6 columns]

In [9]:
ytrain.astype(int)

일   이   삼   사   오   육
0     21  26  27  32  34  42
1      1   9  16  23  24  38
2     13  16  23  31  36  44
3      4   8  18  24  37  45
4      6  10  11  14  36  38
...   ..  ..  ..  ..  ..  ..
1077  16  24  29  40  41  42
1078  14  27  30  31  40  42
1079  11  16  19  21  27  31
1080   9  13  21  25  32  42
1081  10  23  29  33  37  40

[1082 rows x 6 columns]

In [10]:
from pandas import get_dummies

Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)
Xtest

10  16  23  29  33  37  40
1     1   0   0   0   0   0   0
2     0   0   1   0   0   0   0
3     0   0   0   1   0   0   0
4     0   0   0   0   1   0   0
5     0   0   0   0   0   1   0
6     0   0   0   0   0   0   1
보너스   0   1   0   0   0   0   0

In [11]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.2,
                                        random_state = 202309)


In [12]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold
kfold = KFold(n_splits = 10, shuffle = True, random_state = 202309)

In [13]:
!pip install KNN
!pip install SVC
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3111 sha256=e5f2f686c5a44f8fe23e1b817dc24d59de7e183fe6688a6ff3ee7f2defb734cb
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVC: filename=SVC-0.1-py3-none-any.whl size=1870 sha256=acfb9df81949e5beb423f3b28958b227623dff7a154415aa230100848c65ef4b
  Stored in directory: /root/.cache/pip/wheels/88/51/46/316b33cfa9e39d0749762daa17b6a8646e3050079185747370
Successfully built SVC
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 4.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81843 sha256=3614c62a1cde11b2a628b891f010f65a398f40634fa4ee263b4434c91c45bd15
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce7

In [64]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 100)
model2 = LogisticRegression(random_state = 202309)
model3 = SVC(random_state = 202309, probability = True)
model4 = DecisionTreeClassifier(random_state = 202309,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 202309,
                                max_depth = 2,
                                n_estimators= 5)
model6 = AdaBoostClassifier(random_state = 202309)
model7 = GradientBoostingClassifier(random_state = 202309)
model8 = LGBMClassifier(random_state = 202309)
model9 = XGBClassifier(random_state = 202309, silent = True, verbosity = 0)


In [65]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[ 2. 21. 24. 30. 33. 45.]
 [ 1. 10. 18. 28. 37. 45.]
 [ 1. 10. 18. 19. 32. 44.]
 ...
 [ 6. 10. 18. 19. 41. 43.]
 [ 1. 14. 20. 19. 35. 45.]
 [ 1. 10. 16. 24. 27. 45.]]
DecisionTree :  [[12. 14. 15. 24. 27. 32.]
 [ 4.  6. 10. 11. 32. 37.]
 [ 9. 14. 20. 22. 33. 34.]
 ...
 [ 9. 18. 32. 33. 37. 44.]
 [ 3. 12. 13. 18. 31. 32.]
 [14. 21. 35. 36. 40. 44.]]
RandomForest :  [[ 1. 10. 16. 24. 39. 44.]
 [ 1. 10. 13. 31. 34. 45.]
 [ 1. 10. 13. 31. 34. 45.]
 ...
 [ 1. 10. 13. 31. 34. 45.]
 [ 1.  8. 27. 31. 39. 45.]
 [ 1. 10. 18. 26. 38. 45.]]


In [66]:
# 평가용 함수 - 분류
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

7.968110403987777
9.364524357181839
7.885265966017805


In [ ]:
# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor(random_state = 202307,
#                               max_depth = 3,
#                               n_estimators= 5)
# model.fit(Xtr, ytr)

# rpred = model.predict(Xval)
# rpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, rpred)))

In [ ]:
# from sklearn.ensemble import RandomForestClassifier

# model2 = RandomForestClassifier(random_state = 202307,
#                               max_depth = 5,
#                               n_estimators= 100)
# model2.fit(Xtr, ytr)

# rpred2 = model2.predict(Xval)
# rpred2

In [ ]:
# from sklearn.metrics import roc_auc_score

# print(roc_auc_score(yval, rpred2))

In [ ]:
# from xgboost import XGBRegressor

# xmodel = XGBRegressor(random_state = 6,
#                       max_depth = 5,
#                       n_estimators = 200)
# xmodel.fit(Xtr, ytr)

# xpred = xmodel.predict(Xval)
# xpred

In [ ]:
# from sklearn.metrics import mean_squared_error

# print(np.sqrt(mean_squared_error(yval, xpred)))

In [67]:
pred = model1.predict(Xtest)
pred

array([[ 1., 10., 13., 26., 27., 44.],
       [ 1., 10., 13., 26., 27., 44.],
       [ 1., 10., 13., 26., 39., 44.],
       [ 1., 10., 13., 26., 39., 44.],
       [ 1., 10., 13., 26., 27., 44.],
       [ 1., 10., 13., 26., 39., 44.],
       [ 1., 10., 13., 26., 27., 44.]])

In [68]:
predi = model4.predict(Xtest)
predi

array([[10., 15., 18., 21., 34., 41.],
       [10., 15., 18., 21., 34., 41.],
       [10., 15., 18., 21., 34., 41.],
       [10., 15., 18., 21., 34., 41.],
       [10., 15., 18., 21., 34., 41.],
       [10., 15., 18., 21., 34., 41.],
       [10., 15., 18., 21., 34., 41.]])

In [69]:
predo = model5.predict(Xtest)
predo

array([[ 7., 12., 18., 21., 34., 38.],
       [ 7., 12., 18., 21., 34., 38.],
       [ 7., 12., 18., 21., 34., 38.],
       [ 7., 12., 18., 21., 34., 38.],
       [ 7., 12., 18., 21., 34., 38.],
       [ 7., 12., 18., 21., 34., 38.],
       [ 7., 12., 18., 21., 34., 38.]])