<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/%EC%9B%90%ED%95%AB%EB%B6%84%EB%A5%981108Lotto%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
win = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/로또/data/jlotto.csv', delimiter = ',')
win

array([[ 4.,  7., 17., 18., 38., 44.],
       [ 8., 12., 13., 29., 33., 42.],
       [ 3.,  7., 14., 15., 22., 38.],
       ...,
       [ 6., 16., 34., 37., 39., 40.],
       [ 1.,  3.,  4., 29., 42., 45.],
       [ 6., 14., 30., 31., 40., 41.]])

In [4]:
xn = len(win)

In [5]:
# 숫자를 원핫 인코딩으로 변환
def n2o(numbers):

  oh = np.zeros(45)  # 45개의 빈 칸 만들기

  for i in range(6):            # 6개의 당첨번호를 반복
      oh[int(numbers[i])-1] = 1  # 번호는 1부터 시작하고 인덱스는 0부터 시작하니 1을 빼줌
  return oh

# 원핫 인코딩을 숫자로 변환
def o2n(oh):

  numbers = []

  for i in range(len(oh)):
    if oh[i] == 1:           # oh[i]이 1 이면 해당 번호를 출력
      numbers.append(int(i+1))    # 인덱스 보다 숫자가 1크니까 1더해줌 출력

  return numbers

In [6]:
numbers = win[: , :]  # 이게 문제라서 못 하겠음ㅠ 데이터 프레임이 문제인가?
                      # 데이터 프레임으로 안열고 넘파이 텍스트 가져오기 하니 됨
ohs = list(map(n2o, numbers))

xs = ohs[0:xn -1]
ys = ohs[1:xn]

# 원핫 인코딩 확인
print('ohs')
print('x[0] :' + str(xs[0]))
print('y[0] :' + str(ys[0]))

# 번호 확인
print('numbers')
print('x[0] :' + str(o2n(xs[0])))
print('y[0] :' + str(o2n(ys[0])))

ohs
x[0] :[0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
y[0] :[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
numbers
x[0] :[4, 7, 17, 18, 38, 44]
y[0] :[8, 12, 13, 29, 33, 42]


In [7]:
dys = pd.DataFrame(ys)
dys

0    1    2    3    4    5    6    7    8    9   ...   35   36   37  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1101  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
1102  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
1103  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
1104  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1105  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       38   39   40   41   42   43   44  
0     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  1.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
1101  0.0  1.0  0.0  0.0  0.0  1.0  0.0  
1102  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1103  1.0  1.0  0.0  0.0  0.0  0.0  0.0  
1104  0.0  0.0  0.0  1.0  0.0  0.0  1.0  
1105  0.0  1.0  1.0  0.0  0.0  0.0  0.0  

[1106 rows x 45 columns]

In [8]:
train = (0, int(len(win)*0.7))
val = (int(len(win)*0.6), int(len(win)*0.8))
test = (int(len(win)*0.8), len(win))

print('train : {0}, val : {1}, test : {2}'.format(train, val, test))

train : (0, 774), val : (664, 885), test : (885, 1107)


In [9]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(xs, ys,
                                        test_size = 0.2,
                                        random_state = 20242)

In [10]:
# 교차 검증
# 지표를 하나만 설정할 경우
from sklearn.model_selection import cross_val_score
# 지표를 두개 이상 설정할 경우
from sklearn.model_selection import cross_validate

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold

# KFold 생성
kfold = KFold(n_splits = 10, shuffle = True, random_state = 1)

In [11]:
Xtr

[array([0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        1., 0., 0., 0., 

In [12]:
!pip install KNN
!pip install SVR
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3109 sha256=67f064304a6861a7f66ceb7a60096eeb913ae56571fb2b5d77610a88f1c5a9e0
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVR: filename=SVR-0.5-py3-none-any.whl size=2079 sha256=8907d0969e9f90fdd8b6a990e3d6954f8264c17e973aa83cb1c99464bc211f86
  Stored in directory: /root/.cache/pip/wheels/25/85/6e/397fb3d31fbf18f06b7bd62dc90240815e9eeda8d7013fd5ad
Successfully built SVR
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81841 sha256=c8f22fc77c4deea3d3dedd3f608c0c9fc3986817575cb85be101c36c518fbe22
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce

In [13]:
# 머신러닝 알고리즘 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

model1 = KNeighborsClassifier(n_neighbors = 6,
                              leaf_size = 6)
model2 = LogisticRegression(random_state = 20242)
model3 = SVC(random_state = 20242, probability = True)
model4 = DecisionTreeClassifier(random_state = 20242,
                                max_depth = 50)
model5 = RandomForestClassifier(random_state = 20242,
                                max_depth = 2,
                                n_estimators= 60)
model6 = AdaBoostClassifier(random_state = 20242)
model7 = GradientBoostingClassifier(random_state = 20242)
model8 = LGBMClassifier(random_state = 20242)
model9 = XGBClassifier(random_state = 20242, silent = True, verbosity = 0)

In [14]:
model1.fit(Xtr, ytr)
# model2.fit(Xtr, ytr)
# model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
# model7.fit(Xtr, ytr)
# model8.fit(Xtr, ytr)
model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
# pred2 = model2.predict(Xval)
# pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
# pred7 = model7.predict(Xval)
# pred8 = model8.predict(Xval)
pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('SVM' + pred3)
print('DecisionTree : ', + pred4)
print('RandomForest : ', + pred5)
# print('AdaBoost' + pred6)
# print('GradientBoost' + pred7)
# print('LGBM' + pred8)
# print('XGBoost' + pred9)
# print('Voting(hard)' + pred10)
# print('Voting(soft)' + pred11)

KNN :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
DecisionTree :  [[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
RandomForest :  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# 평가용 함수 - 분류
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

# print('F1')
# print(f1_score(yval, pred1, average = 'macro'))
# print(f1_score(yval, pred4, average = 'macro'))
# print(f1_score(yval, pred5, average = 'macro'))
# print('=======================================')

# print('RAS')
# print(roc_auc_score(yval, pred1, multi_class="ovo"))
# print(roc_auc_score(yval, pred4, multi_class="ovo"))
# print(roc_auc_score(yval, pred5, multi_class="ovo"))
# print('=======================================')

# 낮을수록 좋음
print('MSE')
print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))
print(np.sqrt(mean_squared_error(yval, pred9)))

MSE
0.36896630758937343
0.4789879220078826
0.3651483716701107
0.39706127695565785


In [16]:
xtest = win[-1]
Xtest = n2o(xtest)

In [17]:
from sklearn.neighbors import KNeighborsClassifier

model11 = KNeighborsClassifier(n_neighbors = 6,
                              leaf_size = 6)

model11.fit(xs, ys)

ohkpred = model11.predict(Xtest.reshape(1, -1))
ohkpred
kpred = list(map(o2n, ohkpred))
kpred

[[]]

In [18]:
from sklearn.tree import DecisionTreeClassifier

model77 = DecisionTreeClassifier(random_state = 20242,
                                max_depth = 50)
model77.fit(xs, ys)

ohdpred = model77.predict(Xtest.reshape(1, -1))
ohdpred

dpred = list(map(o2n, ohdpred))
dpred
# dpred = []
# for i in range(len(ohdpred)):
#   if ohdpred[i] == 1:
#     dpred.append(i+1)

# dpred


[[3, 11, 14, 18, 26, 27]]

In [19]:
from sklearn.ensemble import RandomForestClassifier

model88 = RandomForestClassifier(random_state = 20242,
                                max_depth = 2,
                                n_estimators= 60)
model88.fit(xs, ys)

ohrpred = model88.predict(Xtest.reshape(1, -1))
ohrpred
rpred = list(map(o2n, ohrpred))
rpred


[[]]

In [20]:
from xgboost import XGBClassifier

model99 = XGBClassifier(random_state = 20242, silent = True, verbosity = 0)

model99.fit(xs, ys)

ohrpred = model99.predict(Xtest.reshape(1, -1))
ohrpred
rpred = list(map(o2n, ohrpred))
rpred

[[]]