<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/%EC%9B%90%ED%95%AB%ED%9A%8C%EA%B8%B0Lotto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [41]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [42]:
win = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/로또/data/jlotto.csv', delimiter = ',')
win

array([[ 4.,  7., 17., 18., 38., 44.],
       [ 8., 12., 13., 29., 33., 42.],
       [ 3.,  7., 14., 15., 22., 38.],
       ...,
       [10., 12., 29., 31., 40., 44.],
       [ 1.,  7., 21., 30., 35., 38.],
       [ 6., 16., 34., 37., 39., 40.]])

In [43]:
xn = len(win)

In [44]:
# 숫자를 원핫 인코딩으로 변환
def n2o(numbers):

  oh = np.zeros(45)  # 45개의 빈 칸 만들기

  for i in range(6):            # 6개의 당첨번호를 반복
      oh[int(numbers[i])-1] = 1  # 번호는 1부터 시작하고 인덱스는 0부터 시작하니 1을 빼줌
  return oh

# 원핫 인코딩을 숫자로 변환
def o2n(oh):

  numbers = []

  for i in range(len(oh)):
    if oh[i] == 1:           # oh[i]이 1 이면 해당 번호를 출력
      numbers.append(int(i+1))    # 인덱스 보다 숫자가 1크니까 1더해줌 출력

  return numbers

In [45]:
numbers = win[: , :]  # 이게 문제라서 못 하겠음ㅠ 데이터 프레임이 문제인가?
                      # 데이터 프레임으로 안열고 넘파이 텍스트 가져오기 하니 됨
ohs = list(map(n2o, numbers))

xs = ohs[0:xn -1]
ys = ohs[1:xn]

# 원핫 인코딩 확인
print('ohs')
print('x[0] :' + str(xs[0]))
print('y[0] :' + str(ys[0]))

# 번호 확인
print('numbers')
print('x[0] :' + str(o2n(xs[0])))
print('y[0] :' + str(o2n(ys[0])))

ohs
x[0] :[0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
y[0] :[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
numbers
x[0] :[4, 7, 17, 18, 38, 44]
y[0] :[8, 12, 13, 29, 33, 42]


In [46]:
dys = pd.DataFrame(ys)
dys

0    1    2    3    4    5    6    7    8    9   ...   35   36   37  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1099  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
1100  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0   
1101  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
1102  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
1103  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   

       38   39   40   41   42   43   44  
0     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  1.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
1099  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
1100  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1101  0.0  1.0  0.0  0.0  0.0  1.0  0.0  
1102  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1103  1.0  1.0  0.0  0.0  0.0  0.0  0.0  

[1104 rows x 45 columns]

In [47]:
train = (0, int(len(win)*0.7))
val = (int(len(win)*0.6), int(len(win)*0.8))
test = (int(len(win)*0.8), len(win))

print('train : {0}, val : {1}, test : {2}'.format(train, val, test))

train : (0, 773), val : (663, 884), test : (884, 1105)


In [48]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(xs, ys,
                                        test_size = 0.2,
                                        random_state = 20242)

In [49]:
# 교차 검증
# 지표를 하나만 설정할 경우
from sklearn.model_selection import cross_val_score
# 지표를 두개 이상 설정할 경우
from sklearn.model_selection import cross_validate

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold

# KFold 생성
kfold = KFold(n_splits = 10, shuffle = True, random_state = 1)

In [50]:
Xtr

[array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.]),
 array([0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 1., 1., 0., 

In [51]:
!pip install KNN
!pip install SVR
!pip install decisiontree
!pip install voting

In [52]:
# 머신러닝 알고리즘 - 회귀용
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

model1 = KNeighborsRegressor(n_neighbors = 350,
                              leaf_size = 6)
model2 = LinearRegression()
model3 = Ridge(random_state = 20241)
model4 = Lasso(random_state = 20241)
model5 = ElasticNet(random_state = 20241)
model6 = SVR()
model7 = DecisionTreeRegressor(random_state = 20242,
                                max_depth = 50)
model8 = RandomForestRegressor(random_state = 20242,
                                max_depth = 2,
                                n_estimators= 60)
model9 = AdaBoostRegressor(random_state = 20242)
model10 = GradientBoostingRegressor(random_state = 20242)
model11 = LGBMRegressor(random_state = 20242)
model12 = XGBRegressor(random_state = 20242, silent = True, verbosity = 0)

In [53]:
model_list1 = [
    ('m1', KNeighborsRegressor()),
    ('m2', LinearRegression()),
    ('m3', Ridge(random_state = 20242)),
    ('m4', Lasso(random_state = 20242)),
    ('m5', ElasticNet(random_state = 20242)),
    ('m6', SVR()),
    ('m7', DecisionTreeRegressor(random_state = 20242)),
    ('m8', RandomForestRegressor(random_state = 20242)),
    ('m9', AdaBoostRegressor(random_state = 20242)),
    ('m10', GradientBoostingRegressor(random_state = 20242)),
    ('m11', LGBMRegressor(random_state = 20242)),
    ('m12', XGBRegressor(random_state = 20242, silent = True, verbosity = 0)),
]
model13 = VotingRegressor(estimators=20242)

In [55]:
model1.fit(Xtr, ytr)
model2.fit(Xtr, ytr)
model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
model7.fit(Xtr, ytr)
model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)
model12.fit(Xtr, ytr)
# model13.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
pred2 = model2.predict(Xval)
pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
pred7 = model7.predict(Xval)
pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)
pred12 = model12.predict(Xval)
# pred13 = model13.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('Ridge' + pred3)
# print('Lasso' + pred4)
# print('ElasticNet' + pred5)
# print('SVM' + pred6)
print('DecisionTree : ', + pred7)
print('RandomForest : ', + pred8)
# print('AdaBoost' + pred9)
# print('GradientBoost' + pred10)
# print('LGBM' + pred11)
# print('XGBoost' + pred12)
# print('VotingRegressor(hard)' + pred13)

KNN :  [[0.14       0.13428571 0.13428571 ... 0.12       0.13428571 0.17142857]
 [0.13714286 0.13142857 0.11428571 ... 0.15142857 0.11714286 0.14285714]
 [0.13428571 0.13714286 0.12285714 ... 0.12       0.13428571 0.16285714]
 ...
 [0.14285714 0.12       0.12       ... 0.12       0.11428571 0.14571429]
 [0.14285714 0.14857143 0.12857143 ... 0.13428571 0.15428571 0.16      ]
 [0.13714286 0.15142857 0.13428571 ... 0.13714286 0.12571429 0.16857143]]
DecisionTree :  [[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]
RandomForest :  [[0.1395116  0.14261034 0.14041587 ... 0.14255085 0.129631   0.1489798 ]
 [0.13292508 0.12418774 0.1269193  ... 0.13406247 0.12674601 0.1522532 ]
 [0.1247478  0.11735771 0.11755659 ... 0.1340763  0.11695458 0.15522001]
 ...
 [0.14457794 0.1154247  0.12769957 ... 0.1387136  0.12631327 0.13122443]
 [0.13384209 0.13760821 0.12795651 ... 0.14869536 0.14474908 0.1

In [56]:
# 평가함수 - 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 1에 가까울수록 좋음
# 음수가 나오면 평균 값 보는게 나음
print('R2')
print(r2_score(yval, pred1))
print(r2_score(yval, pred2))
print(r2_score(yval, pred3))
print(r2_score(yval, pred4))
print(r2_score(yval, pred5))
# print(r2_score(yval, pred6))
print(r2_score(yval, pred7))
print(r2_score(yval, pred8))
# print(r2_score(yval, pred9))
# print(r2_score(yval, pred10))
print(r2_score(yval, pred11))
print(r2_score(yval, pred12))
# print(r2_score(yval, pred13))
print('=======================================')

# 낮을 수록 좋음
print('MSE')
print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred2)))
print(np.sqrt(mean_squared_error(yval, pred3)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))
# print(np.sqrt(mean_squared_error(yval, pred6)))
print(np.sqrt(mean_squared_error(yval, pred7)))
print(np.sqrt(mean_squared_error(yval, pred8)))
# print(np.sqrt(mean_squared_error(yval, pred9)))
# print(np.sqrt(mean_squared_error(yval, pred10)))
print(np.sqrt(mean_squared_error(yval, pred11)))
print(np.sqrt(mean_squared_error(yval, pred12)))
# print(np.sqrt(mean_squared_error(yval, pred13)))

R2
-0.005301695427221244
-0.05246134095554031
-0.05153853917197975
-0.003805382880591315
-0.003805382880591315
-1.0441292114030087
-0.004383361357942609
-0.16351636137470535
-0.3489129961809213
MSE
0.3403284711262028
0.34816845787718703
0.3480149310643544
0.3400575442480964
0.3400575442480964
0.4832019897474839
0.3401601351614694
0.3659811987845914
0.3934554311238633


In [57]:
xtest = win[-1]
Xtest = n2o(xtest)

In [58]:
from sklearn.neighbors import KNeighborsRegressor

model101 = KNeighborsRegressor(n_neighbors = 6,
                              leaf_size = 6)

model101.fit(xs, ys)

ohkpred = model101.predict(Xtest.reshape(1, -1))
ohkpred
kpred = list(map(o2n, ohkpred))
kpred

[[]]

In [59]:
from sklearn.linear_model import LinearRegression

model22 = LinearRegression()

model22.fit(xs, ys)

ohkpred = model22.predict(Xtest.reshape(1, -1))
ohkpred
kpred = list(map(o2n, ohkpred))
kpred

[[]]

In [60]:
from sklearn.linear_model import Ridge

model33 = Ridge(random_state = 20241)

model33.fit(xs, ys)

ohkpred = model33.predict(Xtest.reshape(1, -1))
ohkpred
kpred = list(map(o2n, ohkpred))
kpred

[[]]

In [61]:
from sklearn.linear_model import Lasso

model44 = Lasso(random_state = 20241)

model44.fit(xs, ys)

ohkpred = model44.predict(Xtest.reshape(1, -1))
ohkpred
kpred = list(map(o2n, ohkpred))
kpred

[[]]

In [62]:
from sklearn.linear_model import ElasticNet

model55 = ElasticNet(random_state = 20241)

model55.fit(xs, ys)

ohkpred = model55.predict(Xtest.reshape(1, -1))
ohkpred
kpred = list(map(o2n, ohkpred))
kpred

[[]]

In [63]:
from sklearn.tree import DecisionTreeRegressor

model77 = DecisionTreeRegressor(random_state = 20242,
                                max_depth = 50)
model77.fit(xs, ys)

ohdpred = model77.predict(Xtest.reshape(1, -1))
ohdpred

dpred = list(map(o2n, ohdpred))
dpred
# dpred = []
# for i in range(len(ohdpred)):
#   if ohdpred[i] == 1:
#     dpred.append(i+1)

# dpred


[[7, 16, 18, 20, 23, 26]]

In [64]:
from sklearn.ensemble import RandomForestRegressor

model88 = RandomForestRegressor(random_state = 20242,
                                max_depth = 2,
                                n_estimators= 60)
model88.fit(xs, ys)

ohrpred = model88.predict(Xtest.reshape(1, -1))
ohrpred
rpred = list(map(o2n, ohrpred))
rpred


[[]]

In [69]:
from xgboost import XGBRegressor

model122 = XGBRegressor(random_state = 20242, silent = True, verbosity = 0)

model122.fit(xs, ys)

ohrpred = model122.predict(Xtest.reshape(1, -1))
ohrpred
rpred = list(map(o2n, ohrpred))
rpred

[[]]