<a href="https://colab.research.google.com/github/YonggunJung/colab/blob/main/%ED%9A%8C%EA%B8%B0Lotto2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/로또/data/lotto2.csv')
df

1   2   3   4   5   6  보너스     일     이     삼     사     오     육
0     11  21  22  30  39  44   31  13.0  14.0  18.0  21.0  34.0  44.0
1     13  14  18  21  34  44   16  11.0  16.0  25.0  27.0  35.0  36.0
2     11  16  25  27  35  36   37   4.0   7.0  17.0  18.0  38.0  44.0
3      4   7  17  18  38  44   36   8.0  12.0  13.0  29.0  33.0  42.0
4      8  12  13  29  33  42    5   3.0   7.0  14.0  15.0  22.0  38.0
...   ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   ...   ...
1098   3  20  28  38  40  43    4  17.0  26.0  29.0  30.0  31.0  43.0
1099  17  26  29  30  31  43   12   6.0   7.0  13.0  28.0  36.0  42.0
1100   6   7  13  28  36  42   41  13.0  14.0  22.0  26.0  37.0  38.0
1101  13  14  22  26  37  38   20  10.0  12.0  29.0  31.0  40.0  44.0
1102  10  12  29  31  40  44    2   NaN   NaN   NaN   NaN   NaN   NaN

[1103 rows x 13 columns]

In [ ]:
Xtrain = df.drop(['일', '이', '삼', '사','오', '육'], axis = 1)
Xtrain

1   2   3   4   5   6  보너스
0     11  21  22  30  39  44   31
1     13  14  18  21  34  44   16
2     11  16  25  27  35  36   37
3      4   7  17  18  38  44   36
4      8  12  13  29  33  42    5
...   ..  ..  ..  ..  ..  ..  ...
1098   3  20  28  38  40  43    4
1099  17  26  29  30  31  43   12
1100   6   7  13  28  36  42   41
1101  13  14  22  26  37  38   20
1102  10  12  29  31  40  44    2

[1103 rows x 7 columns]

In [ ]:
Xtest = Xtrain.iloc[Xtrain.index[-1]]
Xtest

1      10
2      12
3      29
4      31
5      40
6      44
보너스     2
Name: 1102, dtype: int64

In [ ]:
Xtrain.drop(Xtrain.index[-1], inplace = True)
Xtrain

1   2   3   4   5   6  보너스
0     11  21  22  30  39  44   31
1     13  14  18  21  34  44   16
2     11  16  25  27  35  36   37
3      4   7  17  18  38  44   36
4      8  12  13  29  33  42    5
...   ..  ..  ..  ..  ..  ..  ...
1097  12  16  21  24  41  43   15
1098   3  20  28  38  40  43    4
1099  17  26  29  30  31  43   12
1100   6   7  13  28  36  42   41
1101  13  14  22  26  37  38   20

[1102 rows x 7 columns]

In [ ]:
Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)

Xtrain

1   2   3   4   5   6  보너스
0     11  21  22  30  39  44   31
1     13  14  18  21  34  44   16
2     11  16  25  27  35  36   37
3      4   7  17  18  38  44   36
4      8  12  13  29  33  42    5
...   ..  ..  ..  ..  ..  ..  ...
1097  12  16  21  24  41  43   15
1098   3  20  28  38  40  43    4
1099  17  26  29  30  31  43   12
1100   6   7  13  28  36  42   41
1101  13  14  22  26  37  38   20

[1102 rows x 7 columns]

In [ ]:
ytrain = df.drop(['1', '2', '3', '4','5', '6'], axis = 1)
ytrain

보너스     일     이     삼     사     오     육
0      31  13.0  14.0  18.0  21.0  34.0  44.0
1      16  11.0  16.0  25.0  27.0  35.0  36.0
2      37   4.0   7.0  17.0  18.0  38.0  44.0
3      36   8.0  12.0  13.0  29.0  33.0  42.0
4       5   3.0   7.0  14.0  15.0  22.0  38.0
...   ...   ...   ...   ...   ...   ...   ...
1098    4  17.0  26.0  29.0  30.0  31.0  43.0
1099   12   6.0   7.0  13.0  28.0  36.0  42.0
1100   41  13.0  14.0  22.0  26.0  37.0  38.0
1101   20  10.0  12.0  29.0  31.0  40.0  44.0
1102    2   NaN   NaN   NaN   NaN   NaN   NaN

[1103 rows x 7 columns]

In [ ]:
ytrain.dropna(inplace = True)
ytrain

보너스     일     이     삼     사     오     육
0      31  13.0  14.0  18.0  21.0  34.0  44.0
1      16  11.0  16.0  25.0  27.0  35.0  36.0
2      37   4.0   7.0  17.0  18.0  38.0  44.0
3      36   8.0  12.0  13.0  29.0  33.0  42.0
4       5   3.0   7.0  14.0  15.0  22.0  38.0
...   ...   ...   ...   ...   ...   ...   ...
1097   15   3.0  20.0  28.0  38.0  40.0  43.0
1098    4  17.0  26.0  29.0  30.0  31.0  43.0
1099   12   6.0   7.0  13.0  28.0  36.0  42.0
1100   41  13.0  14.0  22.0  26.0  37.0  38.0
1101   20  10.0  12.0  29.0  31.0  40.0  44.0

[1102 rows x 7 columns]

In [ ]:
ytrain =ytrain.astype(int)
ytrain

보너스   일   이   삼   사   오   육
0      31  13  14  18  21  34  44
1      16  11  16  25  27  35  36
2      37   4   7  17  18  38  44
3      36   8  12  13  29  33  42
4       5   3   7  14  15  22  38
...   ...  ..  ..  ..  ..  ..  ..
1097   15   3  20  28  38  40  43
1098    4  17  26  29  30  31  43
1099   12   6   7  13  28  36  42
1100   41  13  14  22  26  37  38
1101   20  10  12  29  31  40  44

[1102 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split

Xtr, Xval, ytr, yval = train_test_split(Xtrain, ytrain,
                                        test_size = 0.15,
                                        random_state = 20241)


In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedGroupKFold

# KFold 생성
kfold = KFold(n_splits = 13, shuffle = True, random_state = 20241)

In [ ]:
!pip install KNN
!pip install SVR
!pip install decisiontree
!pip install voting

  Preparing metadata (setup.py) ... done
  Created wheel for KNN: filename=KNN-1.0.0-py3-none-any.whl size=3109 sha256=dadadbf370dcb4a5e4152aa05b6465fe16e2324004b601367e794f8173d142b8
  Stored in directory: /root/.cache/pip/wheels/db/f0/9c/9da3fdf7ad3d19587a688434d71dbf38ced30bde9fb2975ff7
Successfully built KNN
  Preparing metadata (setup.py) ... done
  Created wheel for SVR: filename=SVR-0.5-py3-none-any.whl size=2079 sha256=63d5a2b1ac6aabcd44af5c2d2532dd4c7562dc67b0b24bce7f0bde66903462e0
  Stored in directory: /root/.cache/pip/wheels/25/85/6e/397fb3d31fbf18f06b7bd62dc90240815e9eeda8d7013fd5ad
Successfully built SVR
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.3/335.3 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for decisiontree: filename=DecisionTree-3.4.3-py3-none-any.whl size=81841 sha256=3655e40ed8d0496f26851a4b7b5d039da0301e3ccea5b94c6d9611ea34ac9069
  Stored in directory: /root/.cache/pip/wheels/59/d4/29/d88ed8e92d4c96a49d195c034b7f0e7ce

In [ ]:

# 머신러닝 알고리즘 - 회귀용
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

model1 = KNeighborsRegressor(n_neighbors = 350,
                              leaf_size = 6)
model2 = LinearRegression()
model3 = Ridge(random_state = 20241)
model4 = Lasso(random_state = 20241)
model5 = ElasticNet(random_state = 20241)
model6 = SVR()
model7 = DecisionTreeRegressor(random_state = 20241,
                                max_depth = 50)
model8 = RandomForestRegressor(random_state = 20241,
                                max_depth = 2,
                                n_estimators= 60)
model9 = AdaBoostRegressor(random_state = 20241)
model10 = GradientBoostingRegressor(random_state = 20241)
model11 = LGBMRegressor(random_state = 20241)
model12 = XGBRegressor(random_state = 20241, silent = True, verbosity = 0)


In [ ]:
model_list1 = [
    ('m1', KNeighborsRegressor()),
    ('m2', LinearRegression()),
    ('m3', Ridge(random_state = 20241)),
    ('m4', Lasso(random_state = 20241)),
    ('m5', ElasticNet(random_state = 20241)),
    ('m6', SVR()),
    ('m7', DecisionTreeRegressor(random_state = 20241)),
    ('m8', RandomForestRegressor(random_state = 20241)),
    ('m9', AdaBoostRegressor(random_state = 20241)),
    ('m10', GradientBoostingRegressor(random_state = 20241)),
    ('m11', LGBMRegressor(random_state = 20241)),
    ('m12', XGBRegressor(random_state = 20241, silent = True, verbosity = 0)),
]
model13 = VotingRegressor(estimators=20241)

In [ ]:
# 성능 값을 담을 리스트
score_list = []
# 학습 모델의 이름을 담을 리스트
model_name_list = []
# 최적으로 튜닝된 학습 모델을 담을 리스트
best_model_list = []

In [ ]:
# 교차 검증을 수행할 학습 모델 리스트
check_list = [
    model1, model2, model3, model4, model5, model6, model7,
    model8, model9, model10, model11, model12, model13
]
# 모델의 이름
check_name_list = [
    'KNN (Basic)', 'LinearRegression (Basic)', 'Ridge (Basic)',
    'Lasso (Basic)', 'ElasticNet (Basic)', 'SVR (Basic)',
    'DecisionTreeRegressor (Basic)', 'RandomForest (Basic)', 'AdaBoost (Basic)',
    'GradientBoosting (Basic)', 'LGBM (Basic)', 'XGBoost (Basic)',
    'Voting (Basic)'

]

In [ ]:

# 교차 검증용
# 지표를 하나만 설정할 경우
from sklearn.model_selection import cross_val_score
# 지표를 두개 이상 설정할 경우
from sklearn.model_selection import cross_validate

# 평가함수 - 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 교차 검증
try:
  for idx, ml in enumerate(check_list):
      score = cross_val_score(ml, Xtr, ytr, scoring='neg_mean_squared_error', cv=kfold)


  #     현재 알고리즘의 이름과 평가 점수의 평균을 출력
      print(f'{check_name_list[idx]} : {score.mean()}')
  #     현재 알고리즘의 이름과 평가 점수의 평균을 리스트에 담는다
      score_list.append(score.mean())
      model_name_list.append(check_name_list[idx])
      best_model_list.append(ml)
except :
  pass

KNN (Basic) : -42.04635735217164
LinearRegression (Basic) : -38.153888113710906
Ridge (Basic) : -38.1538501344773
Lasso (Basic) : -38.02987091285609
ElasticNet (Basic) : -38.079553610745315


In [ ]:
model1.fit(Xtr, ytr)
model2.fit(Xtr, ytr)
model3.fit(Xtr, ytr)
model4.fit(Xtr, ytr)
model5.fit(Xtr, ytr)
# model6.fit(Xtr, ytr)
model7.fit(Xtr, ytr)
model8.fit(Xtr, ytr)
# model9.fit(Xtr, ytr)
# model10.fit(Xtr, ytr)
# model11.fit(Xtr, ytr)
model12.fit(Xtr, ytr)
# model13.fit(Xtr, ytr)

pred1 = model1.predict(Xval)
pred2 = model2.predict(Xval)
pred3 = model3.predict(Xval)
pred4 = model4.predict(Xval)
pred5 = model5.predict(Xval)
# pred6 = model6.predict(Xval)
pred7 = model7.predict(Xval)
pred8 = model8.predict(Xval)
# pred9 = model9.predict(Xval)
# pred10 = model10.predict(Xval)
# pred11 = model11.predict(Xval)
pred12 = model12.predict(Xval)
# pred13 = model13.predict(Xval)

print('KNN : ', pred1)
# print('LogisticRegression' + pred2)
# print('Ridge' + pred3)
# print('Lasso' + pred4)
# print('ElasticNet' + pred5)
# print('SVM' + pred6)
print('DecisionTree : ', + pred7)
print('RandomForest : ', + pred8)
# print('AdaBoost' + pred9)
# print('GradientBoost' + pred10)
# print('LGBM' + pred11)
# print('XGBoost' + pred12)
# print('VotingRegressor(hard)' + pred13)

KNN :  [[13.60571429  6.64285714 12.81714286 ... 26.36       32.85714286
  39.88285714]
 [32.91142857  6.51714286 13.08285714 ... 25.92571429 32.8
  39.15142857]
 [30.38571429  6.88285714 13.44571429 ... 26.38571429 32.46
  39.13142857]
 ...
 [34.99714286  6.48857143 13.24857143 ... 26.01714286 32.78
  39.18857143]
 [11.11428571  6.66571429 12.94285714 ... 26.57428571 32.79714286
  39.85142857]
 [26.69714286  6.66       13.31714286 ... 26.15428571 32.70571429
  39.32571429]]
DecisionTree :  [[13. 10. 11. ... 28. 37. 39.]
 [39.  9. 26. ... 37. 40. 42.]
 [43.  7. 18. ... 33. 36. 40.]
 ...
 [39.  1.  3. ... 14. 18. 28.]
 [ 7. 12. 13. ... 22. 25. 33.]
 [30. 23. 27. ... 38. 42. 43.]]
RandomForest :  [[16.58512098  7.28142891 13.31155947 ... 26.75596044 33.10928577
  40.12806652]
 [38.30707088  6.52014481 13.56827678 ... 26.75602716 33.15338422
  39.24469676]
 [39.59261002  6.46293408 13.57022751 ... 26.95262341 33.28935633
  39.31707562]
 ...
 [39.59261002  6.46293408 13.57022751 ... 26.952

In [ ]:
# from sklearn.linear_model import SGDClassifier

# smodel = SGDClassifier(random_state = 20241)

# smodel.fit(Xtr, ytr)

# spred = smodel.predict(Xval)

# print('SGD : ', + spred)

In [ ]:
# from sklearn.metrics import roc_auc_score

# print(np.sqrt(roc_auc_score(yval, pred1, multi_class="ovo")))
# print(np.sqrt(roc_auc_score(yval, pred4, multi_class="ovo")))
# print(np.sqrt(roc_auc_score(yval, pred5, multi_class="ovo")))

# print(roc_auc_score(yval, pred1, multi_class="ovo"))
# print(roc_auc_score(yval, pred4, multi_class="ovo"))
# print(roc_auc_score(yval, pred5, multi_class="ovo"))


In [ ]:
# 평가함수 - 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 1에 가까울수록 좋음
# 음수가 나오면 평균 값 보는게 나음
print('R2')
print(r2_score(yval, pred1))
print(r2_score(yval, pred4))
print(r2_score(yval, pred5))
print('=======================================')

# 낮을 수록 좋음
print('MSE')
print(np.sqrt(mean_squared_error(yval, pred1)))
print(np.sqrt(mean_squared_error(yval, pred4)))
print(np.sqrt(mean_squared_error(yval, pred5)))

R2
0.12027354617819098
0.14322299673296515
0.14216643084115613
MSE
6.20001529392282
5.922565370370302
5.92476673741118


In [ ]:
pred = model1.predict(Xtest)
pred

array([[18.45428571,  6.66571429, 12.93428571, 19.77142857, 26.25142857,
        33.11142857, 39.88857143],
       [18.44      ,  6.67428571, 12.88571429, 19.74857143, 26.24857143,
        33.10857143, 39.89142857],
       [18.40571429,  6.67142857, 12.88285714, 19.74285714, 26.21714286,
        33.05428571, 39.82      ],
       [18.45714286,  6.66571429, 12.93142857, 19.8       , 26.28      ,
        33.13142857, 39.88857143],
       [18.51142857,  6.66857143, 12.86285714, 19.72      , 26.21142857,
        33.04285714, 39.82      ],
       [18.85142857,  6.66285714, 12.88285714, 19.68      , 26.15714286,
        33.03714286, 39.78      ],
       [18.45428571,  6.66571429, 12.93428571, 19.77142857, 26.25142857,
        33.11142857, 39.88857143]])

In [ ]:
predi = model4.predict(Xtest)
predi

array([[ 0.12718015,  6.25061228, 12.14087415, 18.31093716, 25.39817679,
        33.09290766, 40.76756064],
       [ 0.12718015,  6.25116934, 12.16970969, 18.31514097, 25.39817679,
        33.09290766, 40.76756064],
       [ 0.12718015,  6.25061228, 12.14087415, 18.30542694, 25.39817679,
        33.07793207, 40.76756064],
       [ 0.12718015,  6.25061228, 12.14440853, 18.35627109, 25.41070508,
        33.09290766, 40.76756064],
       [ 0.12718015,  6.26300621, 12.14087415, 18.31093716, 25.39817679,
        33.09290766, 40.74081894],
       [ 1.12153895,  6.25040066, 12.15471305, 18.3202626 , 25.40982845,
        33.10030452, 40.75939864],
       [ 0.12718015,  6.25061228, 12.14087415, 18.32841565, 25.43018506,
        33.09546939, 40.76756064]])

In [ ]:
predo = model5.predict(Xtest)
predo

array([[ 0.12682244,  5.626598  , 12.21598169, 18.18284136, 25.50140124,
        33.31065326, 41.52993199],
       [ 0.12682244,  5.63210008, 12.25443687, 18.22034637, 25.5052787 ,
        33.31065326, 41.52993199],
       [ 0.12682244,  5.626598  , 12.20727241, 18.11539602, 25.46256793,
        33.2809328 , 41.52993199],
       [ 0.12682244,  5.626598  , 12.24173799, 18.2696015 , 25.55935503,
        33.31065326, 41.52993199],
       [ 0.12682244,  5.6535464 , 12.19479907, 18.17216063, 25.4796949 ,
        33.30895099, 41.48343678],
       [ 1.1211971 ,  5.62416466, 12.23296693, 18.19463365, 25.51575803,
        33.32072755, 41.51890892],
       [ 0.12682244,  5.626598  , 12.21598169, 18.21513415, 25.55574365,
        33.33967673, 41.54235929]])

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

model11 = KNeighborsRegressor(n_neighbors = 350,
                              leaf_size = 6)

model11.fit(Xtrain, ytrain)

kpred = model11.predict(Xtest)
kpred

array([[17.44285714,  6.82857143, 13.04571429, 19.77714286, 26.38285714,
        33.07428571, 39.88571429],
       [17.37714286,  6.79428571, 13.03142857, 19.77428571, 26.36571429,
        33.07142857, 39.89142857],
       [17.47714286,  6.83142857, 13.05428571, 19.73714286, 26.36571429,
        33.04857143, 39.85714286],
       [17.41142857,  6.79714286, 13.04      , 19.73428571, 26.34857143,
        33.04571429, 39.86285714],
       [17.39428571,  6.78285714, 12.91142857, 19.67428571, 26.36571429,
        33.08285714, 39.86857143],
       [17.67142857,  6.83428571, 13.04285714, 19.74857143, 26.39428571,
        33.04571429, 39.86      ],
       [17.41142857,  6.79714286, 13.04      , 19.73428571, 26.34857143,
        33.04571429, 39.86285714]])

In [ ]:
from sklearn.tree import DecisionTreeRegressor

model44 = DecisionTreeRegressor(random_state = 20241,
                                max_depth = 50)
model44.fit(Xtrain, ytrain)

dpred = model44.predict(Xtest)
dpred

array([[ 6., 17., 18., 24., 25., 26., 30.],
       [ 6., 17., 18., 24., 25., 26., 30.],
       [ 6., 17., 18., 24., 25., 26., 30.],
       [ 6., 17., 18., 24., 25., 26., 30.],
       [ 6., 17., 18., 24., 25., 26., 30.],
       [ 6., 17., 18., 24., 25., 26., 30.],
       [ 6., 17., 18., 24., 25., 26., 30.]])

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model55 = RandomForestRegressor(random_state = 20241,
                                max_depth = 2,
                                n_estimators= 60)
model55.fit(Xtrain, ytrain)

rpred = model55.predict(Xtest)
rpred

array([[ 5.49794936,  6.55408819, 12.59945243, 19.57491704, 25.77875507,
        32.54957374, 39.59338366],
       [ 5.49794936,  6.55408819, 12.59945243, 19.57491704, 25.77875507,
        32.54957374, 39.59338366],
       [ 5.49794936,  6.55408819, 12.59945243, 19.57491704, 25.77875507,
        32.54957374, 39.59338366],
       [ 5.49794936,  6.55408819, 12.59945243, 19.57491704, 25.77875507,
        32.54957374, 39.59338366],
       [ 5.49794936,  6.55408819, 12.59945243, 19.57491704, 25.77875507,
        32.54957374, 39.59338366],
       [ 5.49794936,  6.55408819, 12.59945243, 19.57491704, 25.77875507,
        32.54957374, 39.59338366],
       [ 5.49794936,  6.55408819, 12.59945243, 19.57491704, 25.77875507,
        32.54957374, 39.59338366]])

In [ ]:
a = [17.44285714,  6.82857143, 13.04571429, 19.77714286, 26.38285714,
33.07428571, 39.88571429, 17.37714286,  6.79428571, 13.03142857, 19.77428571, 26.36571429,
33.07142857, 39.89142857, 7.47714286,  6.83142857, 13.05428571, 19.73714286, 26.36571429,
33.04857143, 39.85714286, 17.41142857,  6.79714286, 13.04      , 19.73428571, 26.34857143,
33.04571429, 39.86285714, 17.39428571,  6.78285714, 12.91142857, 19.67428571, 26.36571429,
33.08285714, 39.86857143, 17.67142857,  6.83428571, 13.04285714, 19.74857143, 26.39428571,
33.04571429, 39.86, 17.41142857,  6.79714286, 13.04      , 19.73428571, 26.34857143,
33.04571429, 39.86285714,  6., 17., 18., 24., 25., 26., 30,
6., 17., 18., 24., 25., 26., 30., 6., 17., 18., 24., 25., 26., 30, 6., 17., 18., 24., 25., 26., 30, 6., 17., 18., 24., 25., 26., 30, 6., 17., 18., 24., 25., 26., 30, 6., 17., 18., 24., 25., 26., 30,
6.73714286, 13.02  , 19.57714286, 25.93142857, 32.86285714,
39.71142857, 6.73714286, 13.02571429, 19.61142857, 25.95142857, 32.85142857,
39.68,  6.73714286, 13.06285714, 19.65428571, 26.00857143, 32.90285714,
39.71142857, 6.73714286, 13.02 , 19.57714286, 25.93142857, 32.86285714,
39.71142857, 6.74285714, 13.02      , 19.64857143, 25.99428571, 32.90571429,
39.71428571, 6.76      , 13.03714286, 19.63714286, 25.97428571, 32.88857143,
39.69714286,  6.10415418, 11.50557819, 17.74067529, 23.91929213, 31.54838724,
38.40005642, 6.10415418, 11.50557819, 17.74067529, 23.91929213, 31.54838724,
38.40005642, 6.10415418, 11.50557819, 17.74067529, 23.91929213, 31.54838724,
38.40005642, 6.10415418, 11.50557819, 17.74067529, 23.91929213, 31.54838724,
38.40005642, 6.10415418, 11.50557819, 17.74067529, 23.91929213, 31.54838724,
38.40005642, 6.10415418, 11.50557819, 17.74067529, 23.91929213, 31.54838724,
38.40005642, 4., 12., 24., 27., 28., 32, 4., 12., 24., 27., 28., 32, 4., 12., 24., 27., 28., 32, 4., 12., 24., 27., 28., 32, 4., 12., 24., 27., 28., 32, 4., 12., 24., 27., 28., 32,
1, 10, 13, 26, 39, 45, 1, 10, 13, 26, 39, 45,
1, 10, 13, 26, 39, 45,
1, 10, 13, 26, 39, 45,
1, 10, 13, 26, 39, 45,
1, 10, 13, 26, 39, 45,
11, 12, 18, 21, 31, 38,
11, 12, 18, 21, 31, 38,
11, 12, 18, 21, 31, 38,
11, 12, 18, 21, 31, 38,
11, 12, 18, 21, 31, 38,
10, 10, 18, 21, 34, 33,
10, 10, 18, 21, 34, 33,
10, 10, 18, 21, 34, 33,
10, 10, 18, 21, 34, 33,
10, 10, 18, 21, 34, 33,
10, 10, 18, 21, 34, 33,
4, 11, 13, 26, 38, 45,
4, 11, 13, 26, 38, 45,
4, 11, 13, 26, 38, 45,
1, 11, 13, 26, 38, 45,
1, 11, 13, 26, 38, 45,
4, 11, 13, 26, 38, 45,
4, 11, 13, 26, 38, 45,
10, 15, 18, 21, 34, 41,
10, 15, 18, 21, 34, 41,
10, 15, 18, 21, 34, 41,
10, 15, 18, 21, 34, 41,
10, 15, 18, 21, 34, 41,
10, 15, 18, 21, 34, 41,
10, 15, 18, 21, 34, 41, 2, 12, 18, 21, 31, 45, 2, 12, 18, 21, 31, 45, 2, 12, 18, 21, 31, 45, 2, 12, 18, 21, 31, 45, 2, 12, 18, 21, 31, 4, 2, 12, 18, 21, 31, 45, 2, 12, 18, 21, 31, 45]




In [ ]:
b = []
for num in a:
  b.append(round(num))
b

[17,
 7,
 13,
 20,
 26,
 33,
 40,
 17,
 7,
 13,
 20,
 26,
 33,
 40,
 7,
 7,
 13,
 20,
 26,
 33,
 40,
 17,
 7,
 13,
 20,
 26,
 33,
 40,
 17,
 7,
 13,
 20,
 26,
 33,
 40,
 18,
 7,
 13,
 20,
 26,
 33,
 40,
 17,
 7,
 13,
 20,
 26,
 33,
 40,
 6,
 17,
 18,
 24,
 25,
 26,
 30,
 6,
 17,
 18,
 24,
 25,
 26,
 30,
 6,
 17,
 18,
 24,
 25,
 26,
 30,
 6,
 17,
 18,
 24,
 25,
 26,
 30,
 6,
 17,
 18,
 24,
 25,
 26,
 30,
 6,
 17,
 18,
 24,
 25,
 26,
 30,
 6,
 17,
 18,
 24,
 25,
 26,
 30,
 7,
 13,
 20,
 26,
 33,
 40,
 7,
 13,
 20,
 26,
 33,
 40,
 7,
 13,
 20,
 26,
 33,
 40,
 7,
 13,
 20,
 26,
 33,
 40,
 7,
 13,
 20,
 26,
 33,
 40,
 7,
 13,
 20,
 26,
 33,
 40,
 6,
 12,
 18,
 24,
 32,
 38,
 6,
 12,
 18,
 24,
 32,
 38,
 6,
 12,
 18,
 24,
 32,
 38,
 6,
 12,
 18,
 24,
 32,
 38,
 6,
 12,
 18,
 24,
 32,
 38,
 6,
 12,
 18,
 24,
 32,
 38,
 4,
 12,
 24,
 27,
 28,
 32,
 4,
 12,
 24,
 27,
 28,
 32,
 4,
 12,
 24,
 27,
 28,
 32,
 4,
 12,
 24,
 27,
 28,
 32,
 4,
 12,
 24,
 27,
 28,
 32,
 4,
 12,
 24,
 27,
 28,
 32,
 1,

In [ ]:
c = {} #딕셔너리 선언

for i in b:
    if i in c:
        c[i] += 1
    else:
        c[i] = 1

c

{17: 12,
 7: 14,
 13: 26,
 20: 13,
 26: 33,
 33: 19,
 40: 13,
 18: 39,
 6: 13,
 24: 19,
 25: 7,
 30: 7,
 12: 24,
 32: 12,
 38: 18,
 4: 12,
 27: 6,
 28: 6,
 1: 8,
 10: 25,
 39: 6,
 45: 19,
 11: 12,
 21: 25,
 31: 12,
 34: 13,
 15: 7,
 41: 7,
 2: 7}